
Module‡

ImportFrom

level0
internalRolebody≥
PreviousNoops

end_lineno3
internalRolenoops_previoush
NoopLine
internalRolelines";# Generated by the protocol buffer compiler.  DO NOT EDIT!
*:äM
NoopLine
internalRolelines" # source: protocol-buffer.proto
*:ä.
NoopLine
internalRolelines"
*:ä*:å`
ImportFrom.names
promotedPropertyListtrue.
alias
asname_descriptor"
descriptor:1"google.protobuf*:/§

ImportFrom
internalRolebody

level0Z
ImportFrom.names
promotedPropertyListtrue(
alias
asname_message"message:1"google.protobuf*:/™

ImportFrom
internalRolebody

level0`
ImportFrom.names
promotedPropertyListtrue.
alias
asname_reflection"
reflection:1"google.protobuf*:/®

ImportFrom
internalRolebody

level0^
ImportFrom.names
promotedPropertyListtrue,
alias
asname<nil>"descriptor_pb2:1"google.protobuf*:/ú
Assign
internalRolebody•
Name
ctxStore
internalRoletargetsﬁ
PreviousNoops

end_lineno12
internalRolenoops_previousQ
NoopLine
internalRolelines"$# @@protoc_insertion_point(imports)
*:ä.
NoopLine
internalRolelines"
*	:ä.
NoopLine
internalRolelines"
*
:ä.
NoopLine
internalRolelines"
*:ä.
NoopLine
internalRolelines"
*:ä*:å"
DESCRIPTOR*:É…
Call
internalRolevalueã
	Attribute
ctxLoad
internalRolefunc@
Name
ctxLoad
internalRolevalue"_descriptor*:"FileDescriptor*:iiy
keyword
internalRolekeywordsG
StringLiteral
internalRolevalue"protocol-buffer.proto*:ym"name*:kn
keyword
internalRolekeywords9
StringLiteral
internalRolevalue"persons*:ym"package*:k•
keyword
internalRolekeywordsj
StringLiteral
internalRolevalue"8
protocol-buffer.protopersons"
Person
name (	*:ym"serialized_pb*:k*:gÑ*:ÇÜ!
Assign
internalRolebodyœ
Name
ctxStore
internalRoletargetsã
PreviousNoops

end_lineno20
internalRolenoops_previous.
NoopLine
internalRolelines"
*:ä.
NoopLine
internalRolelines"
*:ä.
NoopLine
internalRolelines"
*:ä.
NoopLine
internalRolelines"
*:ä*:å"_PERSON*:Éâ
Call
internalRolevalueá
	Attribute
ctxLoad
internalRolefunc@
Name
ctxLoad
internalRolevalue"_descriptor*:"
Descriptor*:iij
keyword
internalRolekeywords8
StringLiteral
internalRolevalue"Person*:ym"name*:kw
keyword
internalRolekeywords@
StringLiteral
internalRolevalue"persons.Person*:ym"	full_name*:kk
keyword
internalRolekeywords5
NoneLiteral
internalRolevalue"<nil>*:um"filename*:kr
keyword
internalRolekeywords@
Name
internalRolevalue
ctxLoad"
DESCRIPTOR*:m"file*:kr
keyword
internalRolekeywords5
NoneLiteral
internalRolevalue"<nil>*:um"containing_type*:k¸
keyword
internalRolekeywords«
List
ctxLoad
internalRolevalueê
Call
internalRoleeltså
	Attribute
ctxLoad
internalRolefunc@
Name
ctxLoad
internalRolevalue"_descriptor*:"FieldDescriptor*:iih
keyword
internalRolekeywords6
StringLiteral
internalRolevalue"name*:ym"name*:k|
keyword
internalRolekeywordsE
StringLiteral
internalRolevalue"persons.Person.name*:ym"	full_name*:ks
keyword
internalRolekeywords@

NumLiteral
NumTypeint
internalRolevalue"0*;:vm"index*:kt
keyword
internalRolekeywords@

NumLiteral
NumTypeint
internalRolevalue"1*:vm"number*:kr
keyword
internalRolekeywords@

NumLiteral
NumTypeint
internalRolevalue"9*:vm"type*:kv
keyword
internalRolekeywords@

NumLiteral
NumTypeint
internalRolevalue"9*":vm"cpp_type*:ks
keyword
internalRolekeywords@

NumLiteral
NumTypeint
internalRolevalue"2*+:vm"label*:kt
keyword
internalRolekeywords5
BoolLiteral
internalRolevalue"false*:om"has_default_value*:kã
keyword
internalRolekeywordsœ
Call
internalRolevalue/
StringLiteral
internalRoleargs*6:yj6
StringLiteral
internalRoleargs"utf-8*::yj=
Name
ctxLoad
internalRolefunc"unicode*.:ii*.:mg"default_value*:ko
keyword
internalRolekeywords5
NoneLiteral
internalRolevalue"<nil>* :um"message_type*:kl
keyword
internalRolekeywords5
NoneLiteral
internalRolevalue"<nil>* $:um"	enum_type*:kr
keyword
internalRolekeywords5
NoneLiteral
internalRolevalue"<nil>* ::um"containing_type*:ko
keyword
internalRolekeywords5
BoolLiteral
internalRolevalue"false*!:om"is_extension*:kr
keyword
internalRolekeywords5
NoneLiteral
internalRolevalue"<nil>*!+:um"extension_scope*:kj
keyword
internalRolekeywords5
NoneLiteral
internalRolevalue"<nil>*":um"options*:k*:g*
:sm"fields*:kl
keyword
internalRolekeywords4
List
ctxLoad
internalRolevalue*$:sm"
extensions*:kn
keyword
internalRolekeywords4
List
ctxLoad
internalRolevalue*&:sm"nested_types*:kl
keyword
internalRolekeywords4
List
ctxLoad
internalRolevalue*':sm"
enum_types*:kj
keyword
internalRolekeywords5
NoneLiteral
internalRolevalue"<nil>*):um"options*:kp
keyword
internalRolekeywords5
BoolLiteral
internalRolevalue"false**:om"is_extendable*:kr
keyword
internalRolekeywords4
List
ctxLoad
internalRolevalue*+:sm"extension_ranges*:k
keyword
internalRolekeywordsA

NumLiteral
internalRolevalue
NumTypeint"34*,:vm"serialized_start*:k}
keyword
internalRolekeywordsA

NumLiteral
NumTypeint
internalRolevalue"56*-:vm"serialized_end*:k*:gÑ*:Çë
Assign
internalRolebody¶
	Subscript
ctxStore
internalRoletargetsW
Index
internalRoleslice7
StringLiteral
internalRolevalue"Person*0":yé
	Attribute
ctxLoad
internalRolevalueº
Name
ctxLoad
internalRolevalue{
PreviousNoops

end_lineno47
internalRolenoops_previous.
NoopLine
internalRolelines"
*/:ä*/:å"
DESCRIPTOR*0:"message_types_by_name*0:*0:É>
Name
ctxLoad
internalRolevalue"_PERSON*0.:Ñ*0:Çô
ClassDef
internalRolebodyõ
ClassDef.bases
promotedPropertyListtrueÁ
	Attribute
ctxLoad∫
Name
ctxLoad
internalRolevalue{
PreviousNoops

end_lineno49
internalRolenoops_previous.
NoopLine
internalRolelines"
*1:ä*1:å"_message*2:"Message*2::<∆
ClassDef.body
promotedPropertyListtrue¯
AssignG
Name
ctxStore
internalRoletargets"__metaclass__*3:Éö
	Attribute
ctxLoad
internalRolevalue@
Name
ctxLoad
internalRolevalue"_reflection*3:"GeneratedProtocolMessageType*3:Ñ*3:Çò
AssignD
Name
ctxStore
internalRoletargets"
DESCRIPTOR*4:É>
Name
internalRolevalue
ctxLoad"_PERSON*4:Ñ*4:Ç:;"Person*2::ù
RemainderNoops
internalRolenoops_remainder

end_lineno58.
NoopLine
internalRolelines"
*5:äf
NoopLine
internalRolelines"9  # @@protoc_insertion_point(class_scope:persons.Person)
*6:ä.
NoopLine
internalRolelines"
*7:ä.
NoopLine
internalRolelines"
*8:äV
NoopLine
internalRolelines")# @@protoc_insertion_point(module_scope)
*9:ä*5:å*:$