package main

import "gopkg.in/bblfsh/sdk.v1/uast"
import "fmt"

func main() {
	fmt.Println(
		`////////////////////////////////////////////////////
// Automatically generated by "generate-roles.go" //
////////////////////////////////////////////////////

#include "roles.h"

#include <stddef.h>

static const char *id_to_roles[] = {`)

	var lastRole int
	for i := 0; ; i++ {
		role := uast.Role(i).String()
		if role == fmt.Sprintf("Role(%d)", i) {
			break
		}
		lastRole = i
		name := "role" + role
		fmt.Printf("    \"%s\",\n", name)
	}
	fmt.Println("};")

	fmt.Println("#define TOTAL_ROLES", lastRole+1)

	fmt.Println(`
const char *RoleNameForId(uint16_t id) {
  if (id >= TOTAL_ROLES) {
    return NULL;
  }
  return id_to_roles[id];
}`)
}
