
CompilationUnitl
PackageDeclaration
internalRolepackage1

SimpleName
internalRolename"test*Q:"package:.÷
ImportDeclaration
internalRoleimports
onDemandtrue
staticfalse˚
QualifiedName
internalRolenameõ
QualifiedName
internalRole	qualifier5

SimpleName
internalRole	qualifier"com*^:5

SimpleName
internalRolename"intellij*b::2

SimpleName
internalRolename"lexer*k::0*W:/¶
ImportDeclaration
staticfalse
internalRoleimports
onDemandfalse 
QualifiedName
internalRolename‚
QualifiedName
internalRole	qualifier˛
QualifiedName
internalRole	qualifierõ
QualifiedName
internalRole	qualifier5

SimpleName
internalRole	qualifier"com*{:5

SimpleName
internalRolename"intellij*::1

SimpleName
internalRolename"psi*à::2

SimpleName
internalRolename"tree*å:::

SimpleName
internalRolename"IElementType*ë::0*t:/¶
ImportDeclaration
internalRoleimports
onDemandtrue
statictrueÀ
QualifiedName
internalRolenameÁ
QualifiedName
internalRole	qualifierÑ
QualifiedName
internalRole	qualifierù
QualifiedName
internalRole	qualifier6

SimpleName
internalRole	qualifier"org*≠:6

SimpleName
internalRolename"intellij*±::5

SimpleName
internalRolename"grammar*∫::1

SimpleName
internalRolename"psi*¬::6

SimpleName
internalRolename"BnfTypes*∆::0*ü:/»∆
TypeDeclaration
internalRoletypes
	interfacefalseã
Javadoc
internalRolejavadoc‡

TagElement
internalRoletags^
TextElement
internalRole	fragments-
text%This class is a scanner generated by *€
g
TextElement
internalRole	fragments6
text.<a href="http://www.jflex.de/">JFlex</a> 1.4.3*Ñf
TextElement
internalRole	fragments5
text-on 28/01/16 11:27 from the specification file*∂ä
TextElement
internalRole	fragmentsY
textQ<tt>/home/abigail/code/intellij-grammar-kit-test/src/test/_GrammarLexer.flex</tt>*Á:ãä4
Modifier
internalRole	modifiers"public*Ω;

SimpleName
internalRolename"_GrammarLexer* :j

SimpleType#
internalRolesuperInterfaceTypes7

SimpleName
internalRolename"	FlexLexer*„:˘
FieldDeclaration 
internalRolebodyDeclarations≠
Javadoc
internalRolejavadocÇ

TagElement
internalRoletags^
TextElement
internalRole	fragments-
text%initial size of the lookahead buffer *ı:ãä5
Modifier
internalRole	modifiers"private*ü4
Modifier
internalRole	modifiers"static*ß3
Modifier
internalRole	modifiers"final*Æ1
PrimitiveType
internalRoletype"int*¥Ω
VariableDeclarationFragment
internalRole	fragments;

SimpleName
internalRolename"ZZ_BUFFERSIZE*∏:F
NumberLiteral
internalRoleinitializer
token16384*»:vŸ
FieldDeclaration 
internalRolebodyDeclarationsñ
Javadoc
internalRolejavadocl

TagElement
internalRoletagsH
TextElement
internalRole	fragments
textlexical states *÷:ãä4
Modifier
internalRole	modifiers"public*Í4
Modifier
internalRole	modifiers"static*Ò3
Modifier
internalRole	modifiers"final*¯1
PrimitiveType
internalRoletype"int*˛µ
VariableDeclarationFragment
internalRole	fragments7

SimpleName
internalRolename"	YYINITIAL*Ç:B
NumberLiteral
internalRoleinitializer

token0*é:vÓ
FieldDeclaration 
internalRolebodyDeclarationsÉ
Javadoc
internalRolejavadocÿ

TagElement
internalRoletagsw
TextElement
internalRole	fragmentsF
text>ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l*ùy
TextElementH
text@ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
internalRole	fragments*·S
TextElement
internalRole	fragments"
textat the beginning of a line*∏k
TextElement
internalRole	fragments:
text2l is of the form l = 2*k, k a non negative integer*ÿ:ãä5
Modifier
internalRole	modifiers"private*ì4
Modifier
internalRole	modifiers"static*õ3
Modifier
internalRole	modifiers"final*¢1
PrimitiveType
internalRoletype"int*®‹
VariableDeclarationFragment
internalRole	fragments9

SimpleName
internalRolename"ZZ_LEXSTATE*¨:∑
ArrayInitializer
internalRoleinitializerB
NumberLiteral
internalRoleexpressions

token0*ƒ:vB
NumberLiteral

token0
internalRoleexpressions*«:v-
	Dimension 
internalRoleextraDimensions2€
FieldDeclaration 
internalRolebodyDeclarations≤
Javadoc
internalRolejavadocá

TagElement
internalRoletagsc
TextElement
internalRole	fragments2
text*Translates characters to character classes*€!:ãä5
Modifier
internalRole	modifiers"private*é#4
Modifier
internalRole	modifiers"static*ñ#3
Modifier
internalRole	modifiers"final*ù#X

SimpleType
internalRoletype4

SimpleName
internalRolename"String*£#:Û
VariableDeclarationFragment
internalRole	fragments<

SimpleName
internalRolename"ZZ_CMAP_PACKED*™#:˙
InfixExpression
operator+
internalRoleinitializerh
StringLiteral
internalRoleleftOperand"/"\11\0\1\1\1\1\1\0\1\1\1\1\22\0\1\1\101\0\1\13"*¿$:yg
StringLiteral
internalRolerightOperand"-"\1\0\1\3\1\14\1\0\1\10\1\0\1\2\3\0\1\12\1\7"*ı%:y\
StringLiteral 
internalRoleextendedOperands""\3\0\1\6\1\4\1\5\1\11\uff8a\0"*®	&:y*¿$:)ª
FieldDeclaration 
internalRolebodyDeclarations≤
Javadoc
internalRolejavadocá

TagElement
internalRoletagsc
TextElement2
text*Translates characters to character classes
internalRole	fragments*÷	):ãä5
Modifier
internalRole	modifiers"private*â
+4
Modifier
internalRole	modifiers"static*ë
+3
Modifier
internalRole	modifiers"final*ò
+Ö
	ArrayType
internalRoletype9
PrimitiveType
internalRoleelementType"char*û
+'
	Dimension
internalRole
dimensions•
VariableDeclarationFragment
internalRole	fragments5

SimpleName
internalRolename"ZZ_CMAP*¶
+:≥
MethodInvocation
internalRoleinitializer;

SimpleName
internalRolename"zzUnpackCMap*∞
+:iB

SimpleName
internalRole	arguments"ZZ_CMAP_PACKED*Ω
+:j:g˝
FieldDeclaration 
internalRolebodyDeclarations∂
Javadoc
internalRolejavadocã

TagElement
internalRoletagsg
TextElement
internalRole	fragments6
text.Translates DFA states to action switch labels.*€
.:ãä5
Modifier
internalRole	modifiers"private*í04
Modifier
internalRole	modifiers"static*ö03
Modifier
internalRole	modifiers"final*°0Ñ
	ArrayType
internalRoletype8
PrimitiveType
internalRoleelementType"int*ß0'
	Dimension
internalRole
dimensions‰
VariableDeclarationFragment
internalRole	fragments7

SimpleName
internalRolename"	ZZ_ACTION*Æ0:q
MethodInvocation
internalRoleinitializer=

SimpleName
internalRolename"zzUnpackAction*∫0:i:gä
FieldDeclaration 
internalRolebodyDeclarations5
Modifier
internalRole	modifiers"private*œ24
Modifier
internalRole	modifiers"static*◊23
Modifier
internalRole	modifiers"final*ﬁ2X

SimpleType
internalRoletype4

SimpleName
internalRolename"String*‰2:◊
VariableDeclarationFragment
internalRole	fragments@

SimpleName
internalRolename"ZZ_ACTION_PACKED_0*Î2:[
StringLiteral
internalRoleinitializer"#"\1\0\1\1\1\2\3\1\1\3\10\0\1\4\1\5"*Ñ3:yÏ
MethodDeclaration
constructorfalse 
internalRolebodyDeclarations5
Modifier
internalRole	modifiers"private*¨54
Modifier
internalRole	modifiers"static*¥5ã
	ArrayType
internalRolereturnType28
PrimitiveType
internalRoleelementType"int*ª5'
	Dimension
internalRole
dimensions=

SimpleName
internalRolename"zzUnpackAction*¬5:4Ÿ
Block
internalRolebody¨
VariableDeclarationStatement
internalRole
statementsÑ
	ArrayType
internalRoletype8
PrimitiveType
internalRoleelementType"int*Ÿ6'
	Dimension
internalRole
dimensionsË
VariableDeclarationFragment
internalRole	fragments4

SimpleName
internalRolename"result*‡6:˜
ArrayCreation
internalRoleinitializerÑ
	ArrayType
internalRoletype8
PrimitiveType
internalRoleelementType"int*Ì6'
	Dimension
internalRole
dimensionsB
NumberLiteral
internalRole
dimensions
token17*Ò6:v¢
VariableDeclarationStatement
internalRole
statements1
PrimitiveType
internalRoletype"int*˙7≤
VariableDeclarationFragment
internalRole	fragments4

SimpleName
internalRolename"offset*˛7:B
NumberLiteral
internalRoleinitializer

token0*á7:vÒ
ExpressionStatement
internalRole
statements∫

Assignment
internalRole
expression
operator=>

SimpleName
internalRoleleftHandSide"offset*é8:Éµ
MethodInvocation
internalRolerightHandSide=

SimpleName
internalRolename"zzUnpackAction*ó8:iF

SimpleName
internalRole	arguments"ZZ_ACTION_PACKED_0*¶8:j:

SimpleName
internalRole	arguments"offset*∫8:j:

SimpleName
internalRole	arguments"result*¬8:j:gÑ*é8:Ç:m
ReturnStatement
internalRole
statements:

SimpleName
internalRole
expression"result*÷9::`:3_^*¨5:?2  
MethodDeclaration
constructorfalse 
internalRolebodyDeclarations5
Modifier
internalRole	modifiers"private*Â<4
Modifier
internalRole	modifiers"static*Ì<8
PrimitiveType
internalRolereturnType2"int*Ù<=

SimpleName
internalRolename"zzUnpackAction*¯<:4‰
SingleVariableDeclaration
internalRole
parameters
varargsfalseX

SimpleType
internalRoletype4

SimpleName
internalRolename"String*á<:5

SimpleName
internalRolename"packed*é<:7*á<:6Ω
SingleVariableDeclaration
internalRole
parameters
varargsfalse1
PrimitiveType
internalRoletype"int*ñ<5

SimpleName
internalRolename"offset*ö<:7*ñ<:6ë
SingleVariableDeclaration
internalRole
parameters
varargsfalseÑ
	ArrayType
internalRoletype8
PrimitiveType
internalRoleelementType"int*¢<'
	Dimension
internalRole
dimensions5

SimpleName
internalRolename"result*©<:7*¢<:6–
Block
internalRolebodyù
VariableDeclarationStatement
internalRole
statements1
PrimitiveType
internalRoletype"int*∑=≠
VariableDeclarationFragment
internalRole	fragments/

SimpleName
internalRolename"i*ª=:B
NumberLiteral
internalRoleinitializer

token0*ø=:vñ
VariableDeclarationStatement
internalRole
statements1
PrimitiveType
internalRoletype"int*Í>¶
VariableDeclarationFragment
internalRole	fragments/

SimpleName
internalRolename"j*Ó>:;

SimpleName
internalRoleinitializer"offset*Ú>:Ç
VariableDeclarationStatement
internalRole
statements1
PrimitiveType
internalRoletype"int*ù?í
VariableDeclarationFragment
internalRole	fragments/

SimpleName
internalRolename"l*°?:¶
MethodInvocation
internalRoleinitializer;

SimpleName
internalRole
expression"packed*•?:h5

SimpleName
internalRolename"length*¨?:i:gÉ
WhileStatement
internalRole
statementsª
InfixExpression
operator<
internalRole
expression7

SimpleName
internalRoleleftOperand"i*¡@:8

SimpleName
internalRolerightOperand"l*≈@:*¡@:Ví
Block
internalRolebodyÖ
VariableDeclarationStatement
internalRole
statements1
PrimitiveType
internalRoletype"int*–Aï
VariableDeclarationFragment
internalRole	fragments3

SimpleName
internalRolename"count*‘A:•
MethodInvocation
internalRoleinitializer;

SimpleName
internalRole
expression"packed*‹A:h5

SimpleName
internalRolename"charAt*„A:i}
PostfixExpression
internalRole	arguments
operator++2

SimpleName
internalRoleoperand"i*ÍA:*ÍA:j:gÖ
VariableDeclarationStatement
internalRole
statements1
PrimitiveType
internalRoletype"int*ˆBï
VariableDeclarationFragment
internalRole	fragments3

SimpleName
internalRolename"value*˙B:•
MethodInvocation
internalRoleinitializer;

SimpleName
internalRole
expression"packed*ÇB:h5

SimpleName
internalRolename"charAt*âB:i}
PostfixExpression
internalRole	arguments
operator++2

SimpleName
internalRoleoperand"i*êB:*êB:j:g›
DoStatement
internalRole
statementsó
ExpressionStatement
internalRolebodyÂ

Assignment
internalRole
expression
operator=‡
ArrayAccess
internalRoleleftHandSide5

SimpleName
internalRolearray"result*üC:x
PostfixExpression
internalRoleindex
operator++2

SimpleName
internalRoleoperand"j*¶C:*¶C::É>

SimpleName
internalRolerightHandSide"value*≠C:Ñ*üC:Ç:Zì
InfixExpression
internalRole
expression
operator>Ç
PrefixExpression
operator--
internalRoleleftOperand6

SimpleName
internalRoleoperand"count*ΩC:*ªC:D
NumberLiteral
internalRolerightOperand

token0*≈C:v*ªC:Y:X:W_^:Uh
ReturnStatement
internalRole
statements5

SimpleName
internalRole
expression"j*⁄E::`:3_^*Â<:?2à
FieldDeclaration 
internalRolebodyDeclarations¡
Javadoc
internalRolejavadocñ

TagElement
internalRoletagsr
TextElement
internalRole	fragmentsA
text9Translates a state to a row index in the transition table*ÔJ:ãä5
Modifier
internalRole	modifiers"private*±L4
Modifier
internalRole	modifiers"static*πL3
Modifier
internalRole	modifiers"final*¿LÑ
	ArrayType
internalRoletype8
PrimitiveType
internalRoleelementType"int*∆L'
	Dimension
internalRole
dimensions‰
VariableDeclarationFragment
internalRole	fragments7

SimpleName
internalRolename"	ZZ_ROWMAP*ÕL:q
MethodInvocation
internalRoleinitializer=

SimpleName
internalRolename"zzUnpackRowMap*ŸL:i:gí
FieldDeclaration 
internalRolebodyDeclarations5
Modifier
internalRole	modifiers"private*ÓN4
Modifier
internalRole	modifiers"static*ˆN3
Modifier
internalRole	modifiers"final*˝NX

SimpleType
internalRoletype4

SimpleName
internalRolename"String*ÉN:ﬂ
VariableDeclarationFragment
internalRole	fragments@

SimpleName
internalRolename"ZZ_ROWMAP_PACKED_0*äN:‚
InfixExpression
internalRoleinitializer
operator+d
StringLiteral
internalRoleleftOperand"+"\0\0\0\15\0\32\0\47\0\64\0\101\0\15\0\116"*£O:yk
StringLiteral
internalRolerightOperand"1"\0\133\0\150\0\165\0\202\0\217\0\234\0\251\0\15"*‘P:yD
StringLiteral 
internalRoleextendedOperands""\0\15"*ãQ:y*£O:)Ï
MethodDeclaration 
internalRolebodyDeclarations
constructorfalse5
Modifier
internalRole	modifiers"private*óS4
Modifier
internalRole	modifiers"static*üSã
	ArrayType
internalRolereturnType28
PrimitiveType
internalRoleelementType"int*¶S'
	Dimension
internalRole
dimensions=

SimpleName
internalRolename"zzUnpackRowMap*≠S:4Ÿ
Block
internalRolebody¨
VariableDeclarationStatement
internalRole
statementsÑ
	ArrayType
internalRoletype8
PrimitiveType
internalRoleelementType"int*ƒT'
	Dimension
internalRole
dimensionsË
VariableDeclarationFragment
internalRole	fragments4

SimpleName
internalRolename"result*ÀT:˜
ArrayCreation
internalRoleinitializerÑ
	ArrayType
internalRoletype8
PrimitiveType
internalRoleelementType"int*ÿT'
	Dimension
internalRole
dimensionsB
NumberLiteral
internalRole
dimensions
token17*‹T:v¢
VariableDeclarationStatement
internalRole
statements1
PrimitiveType
internalRoletype"int*ÂU≤
VariableDeclarationFragment
internalRole	fragments4

SimpleName
internalRolename"offset*ÈU:B
NumberLiteral
internalRoleinitializer

token0*ÚU:vÒ
ExpressionStatement
internalRole
statements∫

Assignment
operator=
internalRole
expression>

SimpleName
internalRoleleftHandSide"offset*˘V:Éµ
MethodInvocation
internalRolerightHandSide=

SimpleName
internalRolename"zzUnpackRowMap*ÇV:iF

SimpleName
internalRole	arguments"ZZ_ROWMAP_PACKED_0*ëV:j:

SimpleName
internalRole	arguments"offset*•V:j:

SimpleName
internalRole	arguments"result*≠V:j:gÑ*˘V:Ç:m
ReturnStatement
internalRole
statements:

SimpleName
internalRole
expression"result*¡W::`:3_^*óS:?2ã
MethodDeclaration
constructorfalse 
internalRolebodyDeclarations5
Modifier
internalRole	modifiers"private*–Z4
Modifier
internalRole	modifiers"static*ÿZ8
PrimitiveType
internalRolereturnType2"int*ﬂZ=

SimpleName
internalRolename"zzUnpackRowMap*„Z:4‰
SingleVariableDeclaration
varargsfalse
internalRole
parametersX

SimpleType
internalRoletype4

SimpleName
internalRolename"String*ÚZ:5

SimpleName
internalRolename"packed*˘Z:7*ÚZ:6Ω
SingleVariableDeclaration
internalRole
parameters
varargsfalse1
PrimitiveType
internalRoletype"int*ÅZ5

SimpleName
internalRolename"offset*ÖZ:7*ÅZ:6ë
SingleVariableDeclaration
internalRole
parameters
varargsfalseÑ
	ArrayType
internalRoletype8
PrimitiveType
internalRoleelementType"int*çZ'
	Dimension
internalRole
dimensions5

SimpleName
internalRolename"result*îZ:7*çZ:6ë
Block
internalRolebodyù
VariableDeclarationStatement
internalRole
statements1
PrimitiveType
internalRoletype"int*¢[≠
VariableDeclarationFragment
internalRole	fragments/

SimpleName
internalRolename"i*¶[:B
NumberLiteral
internalRoleinitializer

token0*™[:vñ
VariableDeclarationStatement
internalRole
statements1
PrimitiveType
internalRoletype"int*–\¶
VariableDeclarationFragment
internalRole	fragments/

SimpleName
internalRolename"j*‘\:;

SimpleName
internalRoleinitializer"offset*ÿ\:Ç
VariableDeclarationStatement
internalRole
statements1
PrimitiveType
internalRoletype"int*É]í
VariableDeclarationFragment
internalRole	fragments/

SimpleName
internalRolename"l*á]:¶
MethodInvocation
internalRoleinitializer;

SimpleName
internalRole
expression"packed*ã]:h5

SimpleName
internalRolename"length*í]:i:gƒ
WhileStatement
internalRole
statementsª
InfixExpression
operator<
internalRole
expression7

SimpleName
internalRoleleftOperand"i*ß^:8

SimpleName
internalRolerightOperand"l*´^:*ß^:V”
Block
internalRolebodyô
VariableDeclarationStatement
internalRole
statements1
PrimitiveType
internalRoletype"int*∂_©
VariableDeclarationFragment
internalRole	fragments2

SimpleName
internalRolename"high*∫_:∫
InfixExpression
internalRoleinitializer
operator<<¶
MethodInvocation
internalRoleleftOperand;

SimpleName
internalRole
expression"packed*¡_:h5

SimpleName
internalRolename"charAt*»_:i}
PostfixExpression
operator++
internalRole	arguments2

SimpleName
internalRoleoperand"i*œ_:*œ_:j:gE
NumberLiteral
internalRolerightOperand
token16*◊_:v*¡_:	í
ExpressionStatement
internalRole
statements€

Assignment
internalRole
expression
operator=‡
ArrayAccess
internalRoleleftHandSide5

SimpleName
internalRolearray"result*·`:x
PostfixExpression
operator++
internalRoleindex2

SimpleName
internalRoleoperand"j*Ë`:*Ë`::É≥
InfixExpression
internalRolerightHandSide
operator|:

SimpleName
internalRoleleftOperand"high*Ô`:ß
MethodInvocation
internalRolerightOperand;

SimpleName
internalRole
expression"packed*ˆ`:h5

SimpleName
internalRolename"charAt*˝`:i}
PostfixExpression
internalRole	arguments
operator++2

SimpleName
internalRoleoperand"i*Ñ`:*Ñ`:j:g*Ô`:Ñ*·`:Ç::W_^:Uh
ReturnStatement
internalRole
statements5

SimpleName
internalRole
expression"j*õb::`:3_^*–Z:?2Î
FieldDeclaration 
internalRolebodyDeclarations¶
Javadoc
internalRolejavadoc|

TagElement
internalRoletagsX
TextElement
internalRole	fragments'
textThe transition table of the DFA*Øf:ãä5
Modifier
internalRole	modifiers"private*◊h4
Modifier
internalRole	modifiers"static*ﬂh3
Modifier
internalRole	modifiers"final*ÊhÑ
	ArrayType
internalRoletype8
PrimitiveType
internalRoleelementType"int*Ïh'
	Dimension
internalRole
dimensions‚
VariableDeclarationFragment
internalRole	fragments6

SimpleName
internalRolename"ZZ_TRANS*Ûh:p
MethodInvocation
internalRoleinitializer<

SimpleName
internalRolename"zzUnpackTrans*˛h:i:gœ
FieldDeclaration 
internalRolebodyDeclarations5
Modifier
internalRole	modifiers"private*íj4
Modifier
internalRole	modifiers"static*öj3
Modifier
internalRole	modifiers"final*°jX

SimpleType
internalRoletype4

SimpleName
internalRolename"String*ßj:ú
VariableDeclarationFragment
internalRole	fragments?

SimpleName
internalRolename"ZZ_TRANS_PACKED_0*Æj:†
InfixExpression
internalRoleinitializer
operator+[
StringLiteral
internalRoleleftOperand"""\1\2\1\3\1\4\1\2\1\5\2\2\1\6\5\2"*∆k:yb
StringLiteral
internalRolerightOperand"("\16\0\1\3\16\0\1\7\16\0\1\10\20\0\1\11"*Ól:yf
StringLiteral 
internalRoleextendedOperands")"\11\0\1\12\20\0\1\13\4\0\1\14\25\0\1\15"*úm:yg
StringLiteral 
internalRoleextendedOperands"*"\10\0\1\16\21\0\1\17\10\0\1\20\12\0\1\21"*Àn:yC
StringLiteral 
internalRoleextendedOperands""\6\0"*˚o:y*∆k:)Í
MethodDeclaration
constructorfalse 
internalRolebodyDeclarations5
Modifier
internalRole	modifiers"private*Üq4
Modifier
internalRole	modifiers"static*éqã
	ArrayType
internalRolereturnType28
PrimitiveType
internalRoleelementType"int*ïq'
	Dimension
internalRole
dimensions<

SimpleName
internalRolename"zzUnpackTrans*úq:4ÿ
Block
internalRolebody≠
VariableDeclarationStatement
internalRole
statementsÑ
	ArrayType
internalRoletype8
PrimitiveType
internalRoleelementType"int*≤r'
	Dimension
internalRole
dimensionsÈ
VariableDeclarationFragment
internalRole	fragments4

SimpleName
internalRolename"result*πr:¯
ArrayCreation
internalRoleinitializerÑ
	ArrayType
internalRoletype8
PrimitiveType
internalRoleelementType"int*∆r'
	Dimension
internalRole
dimensionsC
NumberLiteral
token182
internalRole
dimensions* r:v¢
VariableDeclarationStatement
internalRole
statements1
PrimitiveType
internalRoletype"int*‘s≤
VariableDeclarationFragment
internalRole	fragments4

SimpleName
internalRolename"offset*ÿs:B
NumberLiteral

token0
internalRoleinitializer*·s:vÔ
ExpressionStatement
internalRole
statements∏

Assignment
internalRole
expression
operator=>

SimpleName
internalRoleleftHandSide"offset*Ët:É≥
MethodInvocation
internalRolerightHandSide<

SimpleName
internalRolename"zzUnpackTrans*Òt:iE

SimpleName
internalRole	arguments"ZZ_TRANS_PACKED_0*ˇt:j:

SimpleName
internalRole	arguments"offset*ít:j:

SimpleName
internalRole	arguments"result*öt:j:gÑ*Ët:Ç:m
ReturnStatement
internalRole
statements:

SimpleName
internalRole
expression"result*Æu::`:3_^*Üq:?2é"
MethodDeclaration 
internalRolebodyDeclarations
constructorfalse5
Modifier
internalRole	modifiers"private*Ωx4
Modifier
internalRole	modifiers"static*≈x8
PrimitiveType
internalRolereturnType2"int*Ãx<

SimpleName
internalRolename"zzUnpackTrans*–x:4‰
SingleVariableDeclaration
internalRole
parameters
varargsfalseX

SimpleType
internalRoletype4

SimpleName
internalRolename"String*ﬁx:5

SimpleName
internalRolename"packed*Âx:7*ﬁx:6Ω
SingleVariableDeclaration
internalRole
parameters
varargsfalse1
PrimitiveType
internalRoletype"int*Ìx5

SimpleName
internalRolename"offset*Òx:7*Ìx:6ë
SingleVariableDeclaration
internalRole
parameters
varargsfalseÑ
	ArrayType
internalRoletype8
PrimitiveType
internalRoleelementType"int*˘x'
	Dimension
internalRole
dimensions5

SimpleName
internalRolename"result*Äx:7*˘x:6ï
Block
internalRolebodyù
VariableDeclarationStatement
internalRole
statements1
PrimitiveType
internalRoletype"int*éy≠
VariableDeclarationFragment
internalRole	fragments/

SimpleName
internalRolename"i*íy:B
NumberLiteral
internalRoleinitializer

token0*ñy:vñ
VariableDeclarationStatement
internalRole
statements1
PrimitiveType
internalRoletype"int*¡z¶
VariableDeclarationFragment
internalRole	fragments/

SimpleName
internalRolename"j*≈z:;

SimpleName
internalRoleinitializer"offset*…z:Ç
VariableDeclarationStatement
internalRole
statements1
PrimitiveType
internalRoletype"int*Ù{í
VariableDeclarationFragment
internalRole	fragments/

SimpleName
internalRolename"l*¯{:¶
MethodInvocation
internalRoleinitializer;

SimpleName
internalRole
expression"packed*¸{:h5

SimpleName
internalRolename"length*É{:i:g«
WhileStatement
internalRole
statementsª
InfixExpression
internalRole
expression
operator<7

SimpleName
internalRoleleftOperand"i*ò|:8

SimpleName
internalRolerightOperand"l*ú|:*ò|:V÷
Block
internalRolebodyÖ
VariableDeclarationStatement
internalRole
statements1
PrimitiveType
internalRoletype"int*ß}ï
VariableDeclarationFragment
internalRole	fragments3

SimpleName
internalRolename"count*´}:•
MethodInvocation
internalRoleinitializer;

SimpleName
internalRole
expression"packed*≥}:h5

SimpleName
internalRolename"charAt*∫}:i}
PostfixExpression
internalRole	arguments
operator++2

SimpleName
internalRoleoperand"i*¡}:*¡}:j:gÖ
VariableDeclarationStatement
internalRole
statements1
PrimitiveType
internalRoletype"int*Õ~ï
VariableDeclarationFragment
internalRole	fragments3

SimpleName
internalRolename"value*—~:•
MethodInvocation
internalRoleinitializer;

SimpleName
internalRole
expression"packed*Ÿ~:h5

SimpleName
internalRolename"charAt*‡~:i}
PostfixExpression
internalRole	arguments
operator++2

SimpleName
internalRoleoperand"i*Á~:*Á~:j:g∏
ExpressionStatement
internalRole
statementsÅ
PostfixExpression
operator--
internalRole
expression6

SimpleName
internalRoleoperand"value*Û:*Û::Ê
DoStatement
internalRole
statementsú
ExpressionStatement
internalRolebodyÍ

Assignment
operator=
internalRole
expression„
ArrayAccess
internalRoleleftHandSide6

SimpleName
internalRolearray"result*ÖÄ:z
PostfixExpression
operator++
internalRoleindex3

SimpleName
internalRoleoperand"j*åÄ:*åÄ::É?

SimpleName
internalRolerightHandSide"value*ìÄ:Ñ*ÖÄ:Ç:Zó
InfixExpression
internalRole
expression
operator>Ñ
PrefixExpression
internalRoleleftOperand
operator--7

SimpleName
internalRoleoperand"count*£Ä:*°Ä:E
NumberLiteral
internalRolerightOperand

token0*´Ä:v*°Ä:Y:X:W_^:Ui
ReturnStatement
internalRole
statements6

SimpleName
internalRole
expression"j*¿Ç::`:3_^*Ωx:?2Œ
FieldDeclaration 
internalRolebodyDeclarations6
Modifier
internalRole	modifiers"private*ﬂá5
Modifier
internalRole	modifiers"static*Áá4
Modifier
internalRole	modifiers"final*Óá2
PrimitiveType
internalRoletype"int*Ùáæ
VariableDeclarationFragment
internalRole	fragments?

SimpleName
internalRolename"ZZ_UNKNOWN_ERROR*¯á:C
NumberLiteral
internalRoleinitializer

token0*ãá:v…
FieldDeclaration 
internalRolebodyDeclarations6
Modifier
internalRole	modifiers"private*êà5
Modifier
internalRole	modifiers"static*òà4
Modifier
internalRole	modifiers"final*üà2
PrimitiveType
internalRoletype"int*•àπ
VariableDeclarationFragment
internalRole	fragments:

SimpleName
internalRolename"ZZ_NO_MATCH*©à:C
NumberLiteral
internalRoleinitializer

token1*∑à:vŒ
FieldDeclaration 
internalRolebodyDeclarations6
Modifier
internalRole	modifiers"private*ºâ5
Modifier
internalRole	modifiers"static*ƒâ4
Modifier
internalRole	modifiers"final*Àâ2
PrimitiveType
internalRoletype"int*—âæ
VariableDeclarationFragment
internalRole	fragments?

SimpleName
internalRolename"ZZ_PUSHBACK_2BIG*’â:C
NumberLiteral

token2
internalRoleinitializer*Ëâ:v÷
FieldDeclaration 
internalRolebodyDeclarations6
Modifier
internalRole	modifiers"private*Ìä5
Modifier
internalRole	modifiers"static*ıä4
Modifier
internalRole	modifiers"final*¸äÜ
	ArrayType
internalRoletype:
PrimitiveType
internalRoleelementType"char*Ç ä'
	Dimension
internalRole
dimensionsÒ
VariableDeclarationFragment
internalRole	fragments;

SimpleName
internalRolename"EMPTY_BUFFER*â ä:˘
ArrayCreation
internalRoleinitializerÜ
	ArrayType
internalRoletype:
PrimitiveType
internalRoleelementType"char*ú ä'
	Dimension
internalRole
dimensionsB
NumberLiteral
internalRole
dimensions

token0*° ä:vã
FieldDeclaration 
internalRolebodyDeclarations6
Modifier
internalRole	modifiers"private*ß ã5
Modifier
internalRole	modifiers"static*Ø ã4
Modifier
internalRole	modifiers"final*∂ ã2
PrimitiveType
internalRoletype"int*º ã˚
VariableDeclarationFragment
internalRole	fragments4

SimpleName
internalRolename"YYEOF*¿ ã:ä
PrefixExpression
internalRoleinitializer
operator-?
NumberLiteral
internalRoleoperand

token1*… ã:v*» ã:
FieldDeclaration 
internalRolebodyDeclarations6
Modifier
internalRole	modifiers"private*Œ å5
Modifier
internalRole	modifiers"static*÷ å°

SimpleType
internalRoletype¸
QualifiedName
internalRolenameö
QualifiedName
internalRole	qualifier8

SimpleName
internalRole	qualifier"java*› å:1

SimpleName
internalRolename"io*‚ å::5

SimpleName
internalRolename"Reader*Â å::¶
VariableDeclarationFragment
internalRole	fragments7

SimpleName
internalRolename"zzReader*Ï å:3
NullLiteral
internalRoleinitializer"null:u†
FieldDeclaration 
internalRolebodyDeclarations6
Modifier
internalRole	modifiers"private*≥!è5
Modifier
internalRole	modifiers"static*ª!è4
Modifier
internalRole	modifiers"final*¬!èY

SimpleType
internalRoletype5

SimpleName
internalRolename"String*»!è:È
VariableDeclarationFragment
internalRole	fragments;

SimpleName
internalRolename"ZZ_ERROR_MSG*œ!è:¬
ArrayInitializer
internalRoleinitializerX
StringLiteral
internalRoleexpressions""Unkown internal scanner error"*Ê!ê:yW
StringLiteral
internalRoleexpressions""Error: could not match input"*ã"ë:y^
StringLiteral
internalRoleexpressions"%"Error: pushback value was too large"*Ø"í:y-
	Dimension 
internalRoleextraDimensions2¶
FieldDeclaration 
internalRolebodyDeclarations”
Javadoc
internalRolejavadoc®

TagElement
internalRoletagsÉ
TextElement
internalRole	fragmentsQ
textIZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>*Ê"ñ:ãä6
Modifier
internalRole	modifiers"private*∏#ò5
Modifier
internalRole	modifiers"static*¿#ò4
Modifier
internalRole	modifiers"final*«#òÖ
	ArrayType
internalRoletype9
PrimitiveType
internalRoleelementType"int*Õ#ò'
	Dimension
internalRole
dimensionsÏ
VariableDeclarationFragment
internalRole	fragments;

SimpleName
internalRolename"ZZ_ATTRIBUTE*‘#ò:u
MethodInvocation
internalRoleinitializerA

SimpleName
internalRolename"zzUnpackAttribute*„#ò:i:gé
FieldDeclaration 
internalRolebodyDeclarations6
Modifier
internalRole	modifiers"private*˚#ö5
Modifier
internalRole	modifiers"static*É$ö4
Modifier
internalRole	modifiers"final*ä$öY

SimpleType
internalRoletype5

SimpleName
internalRolename"String*ê$ö:◊
VariableDeclarationFragment
internalRole	fragmentsD

SimpleName
internalRolename"ZZ_ATTRIBUTE_PACKED_0*ó$ö:W
StringLiteral
internalRoleinitializer""\1\0\1\11\4\1\1\11\10\0\2\11"*≥$õ:yà
MethodDeclaration
constructorfalse 
internalRolebodyDeclarations6
Modifier
internalRole	modifiers"private*÷$ù5
Modifier
internalRole	modifiers"static*ﬁ$ùå
	ArrayType
internalRolereturnType29
PrimitiveType
internalRoleelementType"int*Â$ù'
	Dimension
internalRole
dimensionsA

SimpleName
internalRolename"zzUnpackAttribute*Ï$ù:4Ì
Block
internalRolebody∞
VariableDeclarationStatement
internalRole
statementsÖ
	ArrayType
internalRoletype9
PrimitiveType
internalRoleelementType"int*Ü%û'
	Dimension
internalRole
dimensionsÎ
VariableDeclarationFragment
internalRole	fragments5

SimpleName
internalRolename"result*ç%û:˘
ArrayCreation
internalRoleinitializerÖ
	ArrayType
internalRoletype9
PrimitiveType
internalRoleelementType"int*ö%û'
	Dimension
internalRole
dimensionsC
NumberLiteral
internalRole
dimensions
token17*û%û:v•
VariableDeclarationStatement
internalRole
statements2
PrimitiveType
internalRoletype"int*ß%ü¥
VariableDeclarationFragment
internalRole	fragments5

SimpleName
internalRolename"offset*´%ü:C
NumberLiteral

token0
internalRoleinitializer*¥%ü:v˝
ExpressionStatement
internalRole
statements∆

Assignment
internalRole
expression
operator=?

SimpleName
internalRoleleftHandSide"offset*ª%†:Éø
MethodInvocation
internalRolerightHandSideA

SimpleName
internalRolename"zzUnpackAttribute*ƒ%†:iJ

SimpleName
internalRole	arguments"ZZ_ATTRIBUTE_PACKED_0*÷%†:j;

SimpleName
internalRole	arguments"offset*Ì%†:j;

SimpleName
internalRole	arguments"result*ı%†:j:gÑ*ª%†:Ç:n
ReturnStatement
internalRole
statements;

SimpleName
internalRole
expression"result*â&°::`:3_^*÷$ù:?2˛ 
MethodDeclaration
constructorfalse 
internalRolebodyDeclarations6
Modifier
internalRole	modifiers"private*ò&§5
Modifier
internalRole	modifiers"static*†&§9
PrimitiveType
internalRolereturnType2"int*ß&§A

SimpleName
internalRolename"zzUnpackAttribute*´&§:4Á
SingleVariableDeclaration
internalRole
parameters
varargsfalseY

SimpleType
internalRoletype5

SimpleName
internalRolename"String*Ω&§:6

SimpleName
internalRolename"packed*ƒ&§:7*Ω&§:6¿
SingleVariableDeclaration
varargsfalse
internalRole
parameters2
PrimitiveType
internalRoletype"int*Ã&§6

SimpleName
internalRolename"offset*–&§:7*Ã&§:6î
SingleVariableDeclaration
internalRole
parameters
varargsfalseÖ
	ArrayType
internalRoletype9
PrimitiveType
internalRoleelementType"int*ÿ&§'
	Dimension
internalRole
dimensions6

SimpleName
internalRolename"result*ﬂ&§:7*ÿ&§:6Û
Block
internalRolebody†
VariableDeclarationStatement
internalRole
statements2
PrimitiveType
internalRoletype"int*Ì&•Ø
VariableDeclarationFragment
internalRole	fragments0

SimpleName
internalRolename"i*Ò&•:C
NumberLiteral

token0
internalRoleinitializer*ı&•:vô
VariableDeclarationStatement
internalRole
statements2
PrimitiveType
internalRoletype"int*†'¶®
VariableDeclarationFragment
internalRole	fragments0

SimpleName
internalRolename"j*§'¶:<

SimpleName
internalRoleinitializer"offset*®'¶:Ü
VariableDeclarationStatement
internalRole
statements2
PrimitiveType
internalRoletype"int*”'ßï
VariableDeclarationFragment
internalRole	fragments0

SimpleName
internalRolename"l*◊'ß:®
MethodInvocation
internalRoleinitializer<

SimpleName
internalRole
expression"packed*€'ß:h6

SimpleName
internalRolename"length*‚'ß:i:gõ
WhileStatement
internalRole
statementsæ
InfixExpression
operator<
internalRole
expression8

SimpleName
internalRoleleftOperand"i*˜'®:9

SimpleName
internalRolerightOperand"l*˚'®:*˜'®:Vß
Block
internalRolebodyã
VariableDeclarationStatement
internalRole
statements2
PrimitiveType
internalRoletype"int*Ü(©ö
VariableDeclarationFragment
internalRole	fragments4

SimpleName
internalRolename"count*ä(©:©
MethodInvocation
internalRoleinitializer<

SimpleName
internalRole
expression"packed*í(©:h6

SimpleName
internalRolename"charAt*ô(©:i
PostfixExpression
internalRole	arguments
operator++3

SimpleName
internalRoleoperand"i*†(©:*†(©:j:gã
VariableDeclarationStatement
internalRole
statements2
PrimitiveType
internalRoletype"int*¨(™ö
VariableDeclarationFragment
internalRole	fragments4

SimpleName
internalRolename"value*∞(™:©
MethodInvocation
internalRoleinitializer<

SimpleName
internalRole
expression"packed*∏(™:h6

SimpleName
internalRolename"charAt*ø(™:i
PostfixExpression
internalRole	arguments
operator++3

SimpleName
internalRoleoperand"i*∆(™:*∆(™:j:gÊ
DoStatement
internalRole
statementsú
ExpressionStatement
internalRolebodyÍ

Assignment
internalRole
expression
operator=„
ArrayAccess
internalRoleleftHandSide6

SimpleName
internalRolearray"result*’(´:z
PostfixExpression
operator++
internalRoleindex3

SimpleName
internalRoleoperand"j*‹(´:*‹(´::É?

SimpleName
internalRolerightHandSide"value*„(´:Ñ*’(´:Ç:Zó
InfixExpression
internalRole
expression
operator>Ñ
PrefixExpression
internalRoleleftOperand
operator--7

SimpleName
internalRoleoperand"count*Û(´:*Ò(´:E
NumberLiteral
internalRolerightOperand

token0*˚(´:v*Ò(´:Y:X:W_^:Ui
ReturnStatement
internalRole
statements6

SimpleName
internalRole
expression"j*ê)≠::`:3_^*ò&§:?2∫
FieldDeclaration 
internalRolebodyDeclarations•
Javadoc
internalRolejavadoc{

TagElement
internalRoletagsW
TextElement
internalRole	fragments%
textthe current state of the DFA *û)∞:ãä6
Modifier
internalRole	modifiers"private*¿)±2
PrimitiveType
internalRoletype"int*»)±p
VariableDeclarationFragment
internalRole	fragments6

SimpleName
internalRolename"zzState*Ã)±:Ä
FieldDeclaration 
internalRolebodyDeclarations¢
Javadoc
internalRolejavadocx

TagElement
internalRoletagsT
TextElement
internalRole	fragments"
textthe current lexical state *‹)≥:ãä6
Modifier
internalRole	modifiers"private*˚)¥2
PrimitiveType
internalRoletype"int*É*¥∏
VariableDeclarationFragment
internalRole	fragments=

SimpleName
internalRolename"zzLexicalState*á*¥:?

SimpleName
internalRoleinitializer"	YYINITIAL*ò*¥:¢
FieldDeclaration 
internalRolebodyDeclarations°
Javadoc
internalRolejavadocˆ

TagElement
internalRoletagst
TextElement
internalRole	fragmentsB
text:this buffer contains the current text to be matched and is*™*∂\
TextElement
internalRole	fragments*
text"the source of the yytext() string *Î*∑:ãä6
Modifier
internalRole	modifiers"private*í+∏_

SimpleType
internalRoletype;

SimpleName
internalRolename"CharSequence*ö+∏:Æ
VariableDeclarationFragment
internalRole	fragments7

SimpleName
internalRolename"zzBuffer*ß+∏:;
StringLiteral
internalRoleinitializer"""*≤+∏:y◊
FieldDeclaration 
internalRolebodyDeclarationsÁ
Javadoc
internalRolejavadocº

TagElement
internalRoletagsó
TextElement
internalRole	fragmentse
text]this buffer may contains the current text array to be matched when it is cheap to acquire it *Ω+∫:ãä6
Modifier
internalRole	modifiers"private*ü,ªÜ
	ArrayType
internalRoletype:
PrimitiveType
internalRoleelementType"char*ß,ª'
	Dimension
internalRole
dimensionsv
VariableDeclarationFragment
internalRole	fragments<

SimpleName
internalRolename"zzBufferArray*Æ,ª:œ
FieldDeclaration 
internalRolebodyDeclarations∂
Javadoc
internalRolejavadocã

TagElement
internalRoletagsg
TextElement
internalRole	fragments5
text-the textposition at the last accepting state *ƒ,Ω:ãä6
Modifier
internalRole	modifiers"private*ˆ,æ2
PrimitiveType
internalRoletype"int*˛,æt
VariableDeclarationFragment
internalRole	fragments:

SimpleName
internalRolename"zzMarkedPos*Ç-æ:‡
FieldDeclaration 
internalRolebodyDeclarations≈
Javadoc
internalRolejavadocö

TagElement
internalRoletagsv
TextElement
internalRole	fragmentsD
text<the textposition at the last state to be included in yytext *ñ-¿:ãä6
Modifier
internalRole	modifiers"private*◊-¡2
PrimitiveType
internalRoletype"int*ﬂ-¡v
VariableDeclarationFragment
internalRole	fragments<

SimpleName
internalRolename"zzPushbackPos*„-¡:À
FieldDeclaration 
internalRolebodyDeclarations±
Javadoc
internalRolejavadocÜ

TagElement
internalRoletagsb
TextElement
internalRole	fragments0
text(the current text position in the buffer *˘-√:ãä6
Modifier
internalRole	modifiers"private*¶.ƒ2
PrimitiveType
internalRoletype"int*Æ.ƒu
VariableDeclarationFragment
internalRole	fragments;

SimpleName
internalRolename"zzCurrentPos*≤.ƒ:Â
FieldDeclaration 
internalRolebodyDeclarationsÃ
Javadoc
internalRolejavadoc°

TagElement
internalRoletags}
TextElement
internalRole	fragmentsK
textCstartRead marks the beginning of the yytext() string in the buffer *«.∆:ãä6
Modifier
internalRole	modifiers"private*è/«2
PrimitiveType
internalRoletype"int*ó/«t
VariableDeclarationFragment
internalRole	fragments:

SimpleName
internalRolename"zzStartRead*õ/«:©
FieldDeclaration 
internalRolebodyDeclarationsí
Javadoc
internalRolejavadocÁ

TagElement
internalRoletags|
TextElementJ
textBendRead marks the last character in the buffer, that has been read
internalRole	fragments*Ø/…E
TextElement
internalRole	fragments
textfrom input *¯/ :ãä6
Modifier
internalRole	modifiers"private*à0À2
PrimitiveType
internalRoletype"int*ê0Àr
VariableDeclarationFragment
internalRole	fragments8

SimpleName
internalRolename"	zzEndRead*î0À:ª
FieldDeclaration 
internalRolebodyDeclarations—
Javadoc
internalRolejavadoc¶

TagElement
internalRoletagsÅ
TextElement
internalRole	fragmentsO
textGzzAtBOL == true <=> the scanner is currently at the beginning of a line*´0Œ:ãä6
Modifier
internalRole	modifiers"private*˚0–6
PrimitiveType
internalRoletype"boolean*É1–¿
VariableDeclarationFragment
internalRole	fragments6

SimpleName
internalRolename"zzAtBOL*ã1–:N
BooleanLiteral
internalRoleinitializer
booleanValuetrue*ï1–:o–
FieldDeclaration 
internalRolebodyDeclarations∑
Javadoc
internalRolejavadocå

TagElement
internalRoletagsh
TextElement
internalRole	fragments6
text.zzAtEOF == true <=> the scanner is at the EOF *¢1“:ãä6
Modifier
internalRole	modifiers"private*’1”6
PrimitiveType
internalRoletype"boolean*›1”p
VariableDeclarationFragment
internalRole	fragments6

SimpleName
internalRolename"zzAtEOF*Â1”:≠
MethodDeclaration
constructortrue 
internalRolebodyDeclarations5
Modifier
internalRole	modifiers"public*Ñ2÷=

SimpleName
internalRolename"_GrammarLexer*ã2÷:4ﬁ
Block
internalRolebodyπ
ConstructorInvocation
internalRole
statementsÉ
CastExpression
internalRole	arguments°

SimpleType
internalRoletype¸
QualifiedName
internalRolenameö
QualifiedName
internalRole	qualifier8

SimpleName
internalRole	qualifier"java*ß2◊:1

SimpleName
internalRolename"io*¨2◊::5

SimpleName
internalRolename"Reader*Ø2◊::2
NullLiteral
internalRole
expression"null:u:3_^*Ñ2÷:E2ı

MethodDeclaration 
internalRolebodyDeclarations
constructortrue˘
Javadoc
internalRolejavadocs

TagElement
internalRoletagsO
TextElement
internalRole	fragments
textCreates a new scanner*Œ2‹Ÿ

TagElement
tagName@param
internalRoletags6

SimpleName
internalRole	fragments"in*˜2ﬁ:b
TextElement
internalRole	fragments0
text(  the java.io.Reader to read input from.*˘2ﬁ*Ó2ﬁ:ãä5
Modifier
internalRole	modifiers"public*™3‡=

SimpleName
internalRolename"_GrammarLexer*±3‡:4¨
SingleVariableDeclaration
internalRole
parameters
varargsfalse°

SimpleType
internalRoletype¸
QualifiedName
internalRolenameö
QualifiedName
internalRole	qualifier8

SimpleName
internalRole	qualifier"java*ø3‡:1

SimpleName
internalRolename"io*ƒ3‡::5

SimpleName
internalRolename"Reader*«3‡::2

SimpleName
internalRolename"in*Œ3‡:7*ø3‡:6˚
Block
internalRolebody÷
ExpressionStatement
internalRole
statementsü

Assignment
internalRole
expression
operator=õ
FieldAccess
internalRoleleftHandSide7

SimpleName
internalRolename"zzReader*›3·:1
ThisExpression
internalRole
expression:â:É<

SimpleName
internalRolerightHandSide"in*Ë3·:Ñ*ÿ3·:Ç::3_^*≈2€:E2Ñ$
MethodDeclaration
constructorfalse 
internalRolebodyDeclarationsÀ
Javadoc
internalRolejavadocë

TagElement
internalRoletagsm
TextElement
internalRole	fragments;
text3Unpacks the compressed character translation table.*˛3Êﬁ

TagElement
tagName@param
internalRoletags:

SimpleName
internalRole	fragments"packed*√4Ë:c
TextElement
internalRole	fragments1
text)   the packed character translation table*…4Ë*º4Ë´

TagElement
internalRoletags
tagName@returnk
TextElement
internalRole	fragments9
text1         the unpacked character translation table*ˇ4È*¯4È:ãä6
Modifier
internalRole	modifiers"private*π5Î5
Modifier
internalRole	modifiers"static*¡5Îç
	ArrayType
internalRolereturnType2:
PrimitiveType
internalRoleelementType"char*»5Î'
	Dimension
internalRole
dimensions<

SimpleName
internalRolename"zzUnpackCMap*–5Î:4Á
SingleVariableDeclaration
internalRole
parameters
varargsfalseY

SimpleType
internalRoletype5

SimpleName
internalRolename"String*›5Î:6

SimpleName
internalRolename"packed*‰5Î:7*›5Î:6µ
Block
internalRolebody¥
VariableDeclarationStatement
internalRole
statementsÜ
	ArrayType
internalRoletype:
PrimitiveType
internalRoleelementType"char*Ú5Ï'
	Dimension
internalRole
dimensionsÓ
VariableDeclarationFragment
internalRole	fragments2

SimpleName
internalRolename"map*˙5Ï:ˇ
ArrayCreation
internalRoleinitializerÜ
	ArrayType
internalRoletype:
PrimitiveType
internalRoleelementType"char*Ñ6Ï'
	Dimension
internalRole
dimensionsH
NumberLiteral
token0x10000
internalRole
dimensions*â6Ï:v†
VariableDeclarationStatement
internalRole
statements2
PrimitiveType
internalRoletype"int*ó6ÌØ
VariableDeclarationFragment
internalRole	fragments0

SimpleName
internalRolename"i*õ6Ì:C
NumberLiteral
internalRoleinitializer

token0*ü6Ì:v†
VariableDeclarationStatement
internalRole
statements2
PrimitiveType
internalRoletype"int*≈6ÓØ
VariableDeclarationFragment
internalRole	fragments0

SimpleName
internalRolename"j*…6Ó:C
NumberLiteral
internalRoleinitializer

token0*Õ6Ó:v¶
WhileStatement
internalRole
statementsÀ
InfixExpression
internalRole
expression
operator<8

SimpleName
internalRoleleftOperand"i*˙6Ô:F
NumberLiteral
token52
internalRolerightOperand*˛6Ô:v*˙6Ô:V•
Block
internalRolebodyã
VariableDeclarationStatement
internalRole
statements2
PrimitiveType
internalRoletype"int*ä7ö
VariableDeclarationFragment
internalRole	fragments4

SimpleName
internalRolename"count*è7:©
MethodInvocation
internalRoleinitializer<

SimpleName
internalRole
expression"packed*ó7:h6

SimpleName
internalRolename"charAt*û7:i
PostfixExpression
internalRole	arguments
operator++3

SimpleName
internalRoleoperand"i*•7:*•7:j:gå
VariableDeclarationStatement
internalRole
statements3
PrimitiveType
internalRoletype"char*±7Òö
VariableDeclarationFragment
internalRole	fragments4

SimpleName
internalRolename"value*∂7Ò:©
MethodInvocation
internalRoleinitializer<

SimpleName
internalRole
expression"packed*æ7Ò:h6

SimpleName
internalRolename"charAt*≈7Ò:i
PostfixExpression
internalRole	arguments
operator++3

SimpleName
internalRoleoperand"i*Ã7Ò:*Ã7Ò:j:g„
DoStatement
internalRole
statementsô
ExpressionStatement
internalRolebodyÁ

Assignment
operator=
internalRole
expression‡
ArrayAccess
internalRoleleftHandSide3

SimpleName
internalRolearray"map*€7Ú:z
PostfixExpression
operator++
internalRoleindex3

SimpleName
internalRoleoperand"j*ﬂ7Ú:*ﬂ7Ú::É?

SimpleName
internalRolerightHandSide"value*Ê7Ú:Ñ*€7Ú:Ç:Zó
InfixExpression
operator>
internalRole
expressionÑ
PrefixExpression
internalRoleleftOperand
operator--7

SimpleName
internalRoleoperand"count*ˆ7Ú:*Ù7Ú:E
NumberLiteral
internalRolerightOperand

token0*˛7Ú:v*Ù7Ú:Y:X:W_^:Uk
ReturnStatement
internalRole
statements8

SimpleName
internalRole
expression"map*ì8Ù::`:3_^*Ù3Â:?2ÿ
MethodDeclaration
constructorfalse 
internalRolebodyDeclarations5
Modifier
internalRole	modifiers"public*ü8˜4
Modifier
internalRole	modifiers"final*¶8˜9
PrimitiveType
internalRolereturnType2"int*¨8˜=

SimpleName
internalRolename"getTokenStart*∞8˜:4ó
Block
internalRolebodys
ReturnStatement
internalRole
statements@

SimpleName
internalRole
expression"zzStartRead*Ã8¯::`:3_^*ü8˜:E2≈
MethodDeclaration
constructorfalse 
internalRolebodyDeclarations5
Modifier
internalRole	modifiers"public*‡8˚4
Modifier
internalRole	modifiers"final*Á8˚9
PrimitiveType
internalRolereturnType2"int*Ì8˚;

SimpleName
internalRolename"getTokenEnd*Ò8˚:4Ü
Block
internalRolebody·
ReturnStatement
internalRole
statements≠
InfixExpression
internalRole
expression
operator+r
MethodInvocation
internalRoleleftOperand=

SimpleName
internalRolename"getTokenStart*ã9¸:i:gn
MethodInvocation
internalRolerightOperand8

SimpleName
internalRolename"yylength*ù9¸:i:g*ã9¸:):`:3_^*‡8˚:E2â 
MethodDeclaration
constructorfalse 
internalRolebodyDeclarations5
Modifier
internalRole	modifiers"public*∞9ˇ:
PrimitiveType
internalRolereturnType2"void*∑9ˇ5

SimpleName
internalRolename"reset*º9ˇ:4Ì
SingleVariableDeclaration
varargsfalse
internalRole
parameters_

SimpleType
internalRoletype;

SimpleName
internalRolename"CharSequence*¬9ˇ:6

SimpleName
internalRolename"buffer*œ9ˇ:7*¬9ˇ:6ø
SingleVariableDeclaration
varargsfalse
internalRole
parameters2
PrimitiveType
internalRoletype"int*◊9ˇ5

SimpleName
internalRolename"start*€9ˇ:7*◊9ˇ:6Ω
SingleVariableDeclaration
varargsfalse
internalRole
parameters2
PrimitiveType
internalRoletype"int*‚9ˇ3

SimpleName
internalRolename"end*Ê9ˇ:7*‚9ˇ:6∆
SingleVariableDeclaration
internalRole
parameters
varargsfalse2
PrimitiveType
internalRoletype"int*Í9ˇ<

SimpleName
internalRolename"initialState*Ó9ˇ:7*Í9ˇ:6 
Block
internalRolebodyˇ
ExpressionStatement
internalRole
statements»

Assignment
internalRole
expression
operator=A

SimpleName
internalRoleleftHandSide"zzBuffer*Å:Ä:É@

SimpleName
internalRolerightHandSide"buffer*å:Ä:Ñ*Å:Ä:Ç:‡
ExpressionStatement
internalRole
statements©

Assignment
internalRole
expression
operator=F

SimpleName
internalRoleleftHandSide"zzBufferArray*ò:Å:Éõ
MethodInvocation
internalRolerightHandSideŸ
QualifiedName
internalRole
expressionÈ
QualifiedName
internalRole	qualifierÑ
QualifiedName
internalRole	qualifierü
QualifiedName
internalRole	qualifier7

SimpleName
internalRole	qualifier"com*®:Å:7

SimpleName
internalRolename"intellij*¨:Å::3

SimpleName
internalRolename"util*µ:Å::3

SimpleName
internalRolename"text*∫:Å::<

SimpleName
internalRolename"CharArrayUtil*ø:Å::hJ

SimpleName
internalRolename"fromSequenceWithoutCopying*Õ:Å:i;

SimpleName
internalRole	arguments"buffer*Ë:Å:j:gÑ*ò:Å:Ç:§
ExpressionStatement
internalRole
statementsÌ

Assignment
internalRole
expression
operator=E

SimpleName
internalRoleleftHandSide"zzCurrentPos*ı:Ç:É‡

Assignment
internalRolerightHandSide
operator=D

SimpleName
internalRoleleftHandSide"zzMarkedPos*Ñ;Ç:Éœ

Assignment
internalRolerightHandSide
operator=D

SimpleName
internalRoleleftHandSide"zzStartRead*í;Ç:É?

SimpleName
internalRolerightHandSide"start*†;Ç:Ñ*í;Ç:ÑÇ*Ñ;Ç:ÑÇ*ı:Ç:Ç:ã
ExpressionStatement
internalRole
statements‘

Assignment
internalRole
expression
operator=F

SimpleName
internalRoleleftHandSide"zzPushbackPos*´;É:ÉG
NumberLiteral
internalRolerightHandSide

token0*ª;É:vÑ*´;É:Ç:ë
ExpressionStatement
internalRole
statements⁄

Assignment
internalRole
expression
operator=@

SimpleName
internalRoleleftHandSide"zzAtEOF*¬;Ñ:ÉS
BooleanLiteral
booleanValuefalse
internalRolerightHandSide*Õ;Ñ:oÑ*¬;Ñ:Ç:ê
ExpressionStatement
internalRole
statementsŸ

Assignment
internalRole
expression
operator=@

SimpleName
internalRoleleftHandSide"zzAtBOL*ÿ;Ö:ÉR
BooleanLiteral
booleanValuetrue
internalRolerightHandSide*‚;Ö:oÑ*ÿ;Ö:Ç:˝
ExpressionStatement
internalRole
statements∆

Assignment
internalRole
expression
operator=B

SimpleName
internalRoleleftHandSide"	zzEndRead*Ï;Ü:É=

SimpleName
internalRolerightHandSide"end*¯;Ü:Ñ*Ï;Ü:Ç:‰
ExpressionStatement
internalRole
statements≠
MethodInvocation
internalRole
expression7

SimpleName
internalRolename"yybegin*Å<á:iA

SimpleName
internalRole	arguments"initialState*â<á:j:g::3_^*∞9ˇ:E2ﬁ
MethodDeclaration 
internalRolebodyDeclarations
constructorfalseÚ
Javadoc
internalRolejavadocw

TagElement
internalRoletagsS
TextElement
internalRole	fragments!
textRefills the input buffer.*®<ã¨

TagElement
tagName@return
internalRoletagsl
TextElement
internalRole	fragments:
text2      <code>false</code>, iff there was new input.*”<ç*Ã<çü

TagElement
tagName
@exception
internalRoletagsÜ
QualifiedName
internalRole	fragmentsö
QualifiedName
internalRole	qualifier8

SimpleName
internalRole	qualifier"java*ù=è:1

SimpleName
internalRolename"io*¢=è:::

SimpleName
internalRolename"IOException*•=è::S
TextElement
internalRole	fragments!
text  if any I/O-Error occurs*∞=è*ê=è:ãä6
Modifier
internalRole	modifiers"private*“=ë=
PrimitiveType
internalRolereturnType2"boolean*⁄=ë8

SimpleName
internalRolename"zzRefill*‚=ë:4∂

SimpleType$
internalRolethrownExceptionTypesÅ
QualifiedName
internalRolenameö
QualifiedName
internalRole	qualifier8

SimpleName
internalRole	qualifier"java*Ù=ë:1

SimpleName
internalRolename"io*˘=ë:::

SimpleName
internalRolename"IOException*¸=ë::•
Block
internalRolebodyÄ
ReturnStatement
internalRole
statementsM
BooleanLiteral
booleanValuetrue
internalRole
expression*ï>í:o:`:3_^*ü<ä:?2É
MethodDeclaration
constructorfalse 
internalRolebodyDeclarations´
Javadoc
internalRolejavadocÄ

TagElement
internalRoletags\
TextElement
internalRole	fragments*
text"Returns the current lexical state.*¨>ó:ãä5
Modifier
internalRole	modifiers"public*◊>ô4
Modifier
internalRole	modifiers"final*ﬁ>ô9
PrimitiveType
internalRolereturnType2"int*‰>ô7

SimpleName
internalRolename"yystate*Ë>ô:4ö
Block
internalRolebodyv
ReturnStatement
internalRole
statementsC

SimpleName
internalRole
expression"zzLexicalState*ˇ>ö::`:3_^*£>ñ:E2¢	
MethodDeclaration
constructorfalse 
internalRolebodyDeclarationsÚ
Javadoc
internalRolejavadocx

TagElement
internalRoletagsT
TextElement
internalRole	fragments"
textEnters a new lexical state*†?üÕ

TagElement
tagName@param
internalRoletags<

SimpleName
internalRole	fragments"newState*Ã?°:P
TextElement
internalRole	fragments
text the new lexical state*‘?°*≈?°:ãä5
Modifier
internalRole	modifiers"public*Û?£4
Modifier
internalRole	modifiers"final*˙?£:
PrimitiveType
internalRolereturnType2"void*Ä@£7

SimpleName
internalRolename"yybegin*Ö@£:4¬
SingleVariableDeclaration
internalRole
parameters
varargsfalse2
PrimitiveType
internalRoletype"int*ç@£8

SimpleName
internalRolename"newState*ë@£:7*ç@£:6¨
Block
internalRolebodyá
ExpressionStatement
internalRole
statements–

Assignment
internalRole
expression
operator=G

SimpleName
internalRoleleftHandSide"zzLexicalState*°@§:ÉB

SimpleName
internalRolerightHandSide"newState*≤@§:Ñ*°@§:Ç::3_^*ó?û:E2π
MethodDeclaration
constructorfalse 
internalRolebodyDeclarationsƒ
Javadoc
internalRolejavadocô

TagElement
internalRoletagsu
TextElement
internalRole	fragmentsC
text;Returns the text matched by the current regular expression.*Õ@©:ãä5
Modifier
internalRole	modifiers"public*ëA´4
Modifier
internalRole	modifiers"final*òA´f

SimpleType
internalRolereturnType2;

SimpleName
internalRolename"CharSequence*ûA´:6

SimpleName
internalRolename"yytext*´A´:4ã
Block
internalRolebodyÊ
ReturnStatement
internalRole
statements≤
MethodInvocation
internalRole
expression>

SimpleName
internalRole
expression"zzBuffer*¡A¨:h;

SimpleName
internalRolename"subSequence* A¨:i@

SimpleName
internalRole	arguments"zzStartRead*÷A¨:j@

SimpleName
internalRole	arguments"zzMarkedPos*„A¨:j:g:`:3_^*ƒ@®:E2’
MethodDeclaration
constructorfalse 
internalRolebodyDeclarationsÃ
Javadoc
internalRolejavadocŒ

TagElement
internalRoletagsq
TextElement?
text7Returns the character at position <tt>pos</tt> from the
internalRole	fragments*ÇB±G
TextElement
internalRole	fragments
textmatched text.*øB≤n
TextElement
internalRole	fragments<
text4It is equivalent to yytext().charAt(pos), but faster*◊B¥µ

TagElement
internalRoletags
tagName@param7

SimpleName
internalRole	fragments"pos*ùC∂:b
TextElement
internalRole	fragments0
text( the position of the character to fetch.*†C∂Y
TextElement'
textA value from 0 to yylength()-1.
internalRole	fragments*ŸC∑*ñC∂ò

TagElement
internalRoletags
tagName@returnX
TextElement&
text the character at position pos
internalRole	fragments*äDπ*ÉDπ:ãä5
Modifier
internalRole	modifiers"public*±Dª4
Modifier
internalRole	modifiers"final*∏Dª:
PrimitiveType
internalRolereturnType2"char*æDª8

SimpleName
internalRolename"yycharat*√Dª:4Ω
SingleVariableDeclaration
internalRole
parameters
varargsfalse2
PrimitiveType
internalRoletype"int*ÃDª3

SimpleName
internalRolename"pos*–Dª:7*ÃDª:6â
Block
internalRolebody‰
ReturnStatement
internalRole
statements∞
ConditionalExpression
internalRole
expression∆
InfixExpression
internalRole
expression
operator!=D

SimpleName
internalRoleleftOperand"zzBufferArray*‚Dº:5
NullLiteral
internalRolerightOperand"null:u*‚Dº:¥
ArrayAccess
internalRolethenExpression=

SimpleName
internalRolearray"zzBufferArray*˙Dº:≈
InfixExpression
internalRoleindex
operator+B

SimpleName
internalRoleleftOperand"zzStartRead*àEº:;

SimpleName
internalRolerightOperand"pos*îEº:*àEº:)˙
MethodInvocation
internalRoleelseExpression>

SimpleName
internalRole
expression"zzBuffer*ôEº:h6

SimpleName
internalRolename"charAt*¢Eº:i 
InfixExpression
internalRole	arguments
operator+B

SimpleName
internalRoleleftOperand"zzStartRead*©Eº:;

SimpleName
internalRolerightOperand"pos*µEº:*©Eº:j):g:`:3_^*˘A∞:E2°
MethodDeclaration 
internalRolebodyDeclarations
constructorfalse∑
Javadoc
internalRolejavadocå

TagElement
internalRoletagsh
TextElement6
text.Returns the length of the matched text region.
internalRole	fragments*ÃE¡:ãä5
Modifier
internalRole	modifiers"public*ÉF√4
Modifier
internalRole	modifiers"final*äF√9
PrimitiveType
internalRolereturnType2"int*êF√8

SimpleName
internalRolename"yylength*îF√:4´
Block
internalRolebodyÜ
ReturnStatement
internalRole
statements“
InfixExpression
internalRole
expression
operator-B

SimpleName
internalRoleleftOperand"zzMarkedPos*¨Fƒ:C

SimpleName
internalRolerightOperand"zzStartRead*∏Fƒ:*¨Fƒ:*:`:3_^*√E¿:E2¢
MethodDeclaration
constructorfalse 
internalRolebodyDeclarations¢	
Javadoc
internalRolejavadocì

TagElement
internalRoletagsg
TextElement
internalRole	fragments5
text-Reports an error that occured while scanning.*÷F…n
TextElement
internalRole	fragments<
text4In a wellformed scanner (no or only correct usage of*éGÀt
TextElement
internalRole	fragmentsB
text:yypushback(int) and a match-all fallback rule) this method*»GÃw
TextElementE
text=will only be called with things that "Can't Possibly Happen".
internalRole	fragments*àHÕp
TextElement>
text6If this method is called, something is seriously wrong
internalRole	fragments*ÀHŒm
TextElement
internalRole	fragments;
text3(e.g. a JFlex bug producing a faulty scanner etc.).*áIœr
TextElement@
text8Usual syntax/scanner level error handling should be done
internalRole	fragments*≈I—R
TextElement
internalRole	fragments 
textin error fallback rules.*ÉJ“·

TagElement
internalRoletags
tagName@param=

SimpleName
internalRole	fragments"	errorCode*ØJ‘:c
TextElement
internalRole	fragments1
text)  the code of the errormessage to display*∏J‘*¶J‘:ãä6
Modifier
internalRole	modifiers"private*ÍJ÷:
PrimitiveType
internalRolereturnType2"void*ÚJ÷;

SimpleName
internalRolename"zzScanError*˜J÷:4√
SingleVariableDeclaration
internalRole
parameters
varargsfalse2
PrimitiveType
internalRoletype"int*ÉK÷9

SimpleName
internalRolename"	errorCode*áK÷:7*ÉK÷:6¨
Block
internalRolebodyá
VariableDeclarationStatement
internalRole
statementsY

SimpleType
internalRoletype5

SimpleName
internalRolename"String*òK◊:p
VariableDeclarationFragment
internalRole	fragments6

SimpleName
internalRolename"message*üK◊:˝
TryStatement
internalRole
statementsç
Block
internalRolebodyË
ExpressionStatement
internalRole
statements±

Assignment
internalRole
expression
operator=@

SimpleName
internalRoleleftHandSide"message*∏KŸ:É©
ArrayAccess
internalRolerightHandSide<

SimpleName
internalRolearray"ZZ_ERROR_MSG*¬KŸ:9

SimpleName
internalRoleindex"	errorCode*œKŸ::Ñ*∏KŸ:Ç::b_^º
CatchClause
internalRolecatchClausesı
SingleVariableDeclaration
varargsfalse
internalRole	exceptionq

SimpleType
internalRoletypeM

SimpleName
internalRolename"ArrayIndexOutOfBoundsException*ÏK€:0

SimpleName
internalRolename"e*ãL€:*ÏK€ì
Block
internalRolebodyÔ
ExpressionStatement
internalRole
statements∏

Assignment
internalRole
expression
operator=@

SimpleName
internalRoleleftHandSide"message*ñL‹:É∞
ArrayAccess
internalRolerightHandSide<

SimpleName
internalRolearray"ZZ_ERROR_MSG*†L‹:@

SimpleName
internalRoleindex"ZZ_UNKNOWN_ERROR*≠L‹::Ñ*ñL‹:Ç::_^:c:a˝
ThrowStatement
internalRole
statements 
ClassInstanceCreation
internalRole
expressionX

SimpleType
internalRoletype4

SimpleName
internalRolename"Error*’Lﬂ:;

SimpleName
internalRole	arguments"message*€Lﬂ::e:3_^*ÕF»:?2∏
MethodDeclaration
constructorfalse 
internalRolebodyDeclarationsö
Javadoc
internalRolejavadocü

TagElement
internalRoletags
TextElement
internalRole	fragmentsM
textEPushes the specified amount of characters back into the input stream.*ˆL‰z
TextElement
internalRole	fragmentsH
text@They will be read again by then next call of the scanning method*∆MÊÕ

TagElement
internalRoletags
tagName@param:

SimpleName
internalRole	fragments"number*òNË:f
TextElement
internalRole	fragments4
text,  the number of characters to be read again.*ûNËj
TextElement
internalRole	fragments8
text0This number must not be greater than yylength()!*ﬂNÈ*ëNË:ãä5
Modifier
internalRole	modifiers"public*òOÎ:
PrimitiveType
internalRolereturnType2"void*üOÎ:

SimpleName
internalRolename"
yypushback*§OÎ:4¿
SingleVariableDeclaration
internalRole
parameters
varargsfalse2
PrimitiveType
internalRoletype"int*ØOÎ6

SimpleName
internalRolename"number*≥OÎ:7*ØOÎ:6œ
Block
internalRolebodyü
IfStatement
internalRole
statements¯
InfixExpression
operator>
internalRole
expression=

SimpleName
internalRoleleftOperand"number*«OÏ:n
MethodInvocation
internalRolerightOperand8

SimpleName
internalRolename"yylength*–OÏ:i:g*«OÏ:G
ExpressionStatement
internalRolethenStatementµ
MethodInvocation
internalRole
expression;

SimpleName
internalRolename"zzScanError*„OÌ:iE

SimpleName
internalRole	arguments"ZZ_PUSHBACK_2BIG*ÔOÌ:j:g:H"if:Fà
ExpressionStatement
internalRole
statements—

Assignment
internalRole
expression
operator-=D

SimpleName
internalRoleleftHandSide"zzMarkedPos*áPÔ:É@

SimpleName
internalRolerightHandSide"number*ñPÔ:Ñ*áPÔ:ÇÜÖ*::3_^*ÌL„:E2Ì§
MethodDeclaration
constructorfalse 
internalRolebodyDeclarationsÌ
Javadoc
internalRolejavadocè

TagElement
internalRoletagsx
TextElement
internalRole	fragmentsF
text>Resumes scanning until the next regular expression is matched,*ØPÙq
TextElement
internalRole	fragments?
text7the end of input is encountered or an I/O-Error occurs.*ÛPıé

TagElement
tagName@return
internalRoletagsN
TextElement
text      the next token
internalRole	fragments*ºQ˜*µQ˜ü

TagElement
internalRoletags
tagName
@exceptionÜ
QualifiedName
internalRole	fragmentsö
QualifiedName
internalRole	qualifier8

SimpleName
internalRole	qualifier"java*„Q¯:1

SimpleName
internalRolename"io*ËQ¯:::

SimpleName
internalRolename"IOException*ÎQ¯::S
TextElement
internalRole	fragments!
text  if any I/O-Error occurs*ˆQ¯*÷Q¯:ãä5
Modifier
internalRole	modifiers"public*òR˙f

SimpleType
internalRolereturnType2;

SimpleName
internalRolename"IElementType*üR˙:7

SimpleName
internalRolename"advance*¨R˙:4∂

SimpleType$
internalRolethrownExceptionTypesÅ
QualifiedName
internalRolenameö
QualifiedName
internalRole	qualifier8

SimpleName
internalRole	qualifier"java*ΩR˙:1

SimpleName
internalRolename"io*¬R˙:::

SimpleName
internalRolename"IOException*≈R˙::ëô
Block
internalRolebody‡
VariableDeclarationStatement
internalRole
statements2
PrimitiveType
internalRoletype"int*◊R˚p
VariableDeclarationFragment
internalRole	fragments6

SimpleName
internalRolename"zzInput*€R˚:·
VariableDeclarationStatement
internalRole
statements2
PrimitiveType
internalRoletype"int*ËR¸q
VariableDeclarationFragment
internalRole	fragments7

SimpleName
internalRolename"zzAction*ÏR¸:Ê
VariableDeclarationStatement
internalRole
statements2
PrimitiveType
internalRoletype"int*ëSˇv
VariableDeclarationFragment
internalRole	fragments<

SimpleName
internalRolename"zzCurrentPosL*ïSˇ:Â
VariableDeclarationStatement
internalRole
statements2
PrimitiveType
internalRoletype"int*®SÄu
VariableDeclarationFragment
internalRole	fragments;

SimpleName
internalRolename"zzMarkedPosL*¨SÄ:•
VariableDeclarationStatement
internalRole
statements2
PrimitiveType
internalRoletype"int*æSÅ¥
VariableDeclarationFragment
internalRole	fragments9

SimpleName
internalRolename"
zzEndReadL*¬SÅ:?

SimpleName
internalRoleinitializer"	zzEndRead*œSÅ:–
VariableDeclarationStatement
internalRole
statements_

SimpleType
internalRoletype;

SimpleName
internalRolename"CharSequence*ﬁSÇ:≤
VariableDeclarationFragment
internalRole	fragments8

SimpleName
internalRolename"	zzBufferL*ÎSÇ:>

SimpleName
internalRoleinitializer"zzBuffer*˜SÇ:Ç
VariableDeclarationStatement
internalRole
statementsÜ
	ArrayType
internalRoletype:
PrimitiveType
internalRoleelementType"char*ÖTÉ'
	Dimension
internalRole
dimensionsº
VariableDeclarationFragment
internalRole	fragments=

SimpleName
internalRolename"zzBufferArrayL*åTÉ:C

SimpleName
internalRoleinitializer"zzBufferArray*ùTÉ:ı
VariableDeclarationStatement
internalRole
statementsÜ
	ArrayType
internalRoletype:
PrimitiveType
internalRoleelementType"char*∞TÑ'
	Dimension
internalRole
dimensionsØ
VariableDeclarationFragment
internalRole	fragments6

SimpleName
internalRolename"zzCMapL*∏TÑ:=

SimpleName
internalRoleinitializer"ZZ_CMAP*¬TÑ:ˆ
VariableDeclarationStatement
internalRole
statementsÖ
	ArrayType
internalRoletype9
PrimitiveType
internalRoleelementType"int*–TÜ'
	Dimension
internalRole
dimensions±
VariableDeclarationFragment
internalRole	fragments7

SimpleName
internalRolename"zzTransL*◊TÜ:>

SimpleName
internalRoleinitializer"ZZ_TRANS*‚TÜ:¯
VariableDeclarationStatement
internalRole
statementsÖ
	ArrayType
internalRoletype9
PrimitiveType
internalRoleelementType"int*Tá'
	Dimension
internalRole
dimensions≥
VariableDeclarationFragment
internalRole	fragments8

SimpleName
internalRolename"	zzRowMapL*˜Tá:?

SimpleName
internalRoleinitializer"	ZZ_ROWMAP*ÉUá:˘
VariableDeclarationStatement
internalRole
statementsÖ
	ArrayType
internalRoletype9
PrimitiveType
internalRoleelementType"int*íUà'
	Dimension
internalRole
dimensions¥
VariableDeclarationFragment
internalRole	fragments6

SimpleName
internalRolename"zzAttrL*ôUà:B

SimpleName
internalRoleinitializer"ZZ_ATTRIBUTE*£Uà:Ï}
WhileStatement
internalRole
statementsN
BooleanLiteral
booleanValuetrue
internalRole
expression*ΩUä:oVÈ|
Block
internalRolebodyà
ExpressionStatement
internalRole
statements—

Assignment
operator=
internalRole
expressionE

SimpleName
internalRoleleftHandSide"zzMarkedPosL*ÀUã:ÉE

SimpleName
internalRolerightHandSide"zzMarkedPos*⁄Uã:Ñ*ÀUã:Ç:Œ
ExpressionStatement
internalRole
statementsó

Assignment
internalRole
expression
operator=A

SimpleName
internalRoleleftHandSide"zzAction*ÓUç:Éé
PrefixExpression
operator-
internalRolerightHandSide?
NumberLiteral

token1
internalRoleoperand*˙Uç:v*˘Uç:Ñ*ÓUç:Ç:≠
ExpressionStatement
internalRole
statementsˆ

Assignment
operator=
internalRole
expressionF

SimpleName
internalRoleleftHandSide"zzCurrentPosL*ÑVè:ÉË

Assignment
operator=
internalRolerightHandSideE

SimpleName
internalRoleleftHandSide"zzCurrentPos*îVè:É÷

Assignment
internalRolerightHandSide
operator=D

SimpleName
internalRoleleftHandSide"zzStartRead*£Vè:ÉF

SimpleName
internalRolerightHandSide"zzMarkedPosL*±Vè:Ñ*£Vè:ÑÇ*îVè:ÑÇ*ÑVè:Ç:Ï
ExpressionStatement
internalRole
statementsµ

Assignment
operator=
internalRole
expression@

SimpleName
internalRoleleftHandSide"zzState*∆Vë:É≠
ArrayAccess
internalRolerightHandSide;

SimpleName
internalRolearray"ZZ_LEXSTATE*–Vë:>

SimpleName
internalRoleindex"zzLexicalState*‹Vë::Ñ*∆Vë:Ç:«H
LabeledStatement
internalRole
statements;

SimpleName
internalRolelabel"zzForAction*ıVî:ŸG
Block
internalRolebodyµG
WhileStatement
internalRole
statementsN
BooleanLiteral
booleanValuetrue
internalRole
expression*ìWï:oV≤F
Block
internalRolebodyÅ+
IfStatement
internalRole
statements”
InfixExpression
internalRole
expression
operator<D

SimpleName
internalRoleleftOperand"zzCurrentPosL*™Wó:B

SimpleName
internalRolerightOperand"
zzEndReadL*∫Wó:*™Wó:G∑
ExpressionStatement
internalRolethenStatement¸

Assignment
internalRole
expression
operator=@

SimpleName
internalRoleleftHandSide"zzInput*“Wò:ÉÙ
ParenthesizedExpression
internalRolerightHandSideµ
ConditionalExpression
internalRole
expression«
InfixExpression
internalRole
expression
operator!=E

SimpleName
internalRoleleftOperand"zzBufferArrayL*›Wò:5
NullLiteral
internalRolerightOperand"null:u*›Wò:ˆ
ArrayAccess
internalRolethenExpression>

SimpleName
internalRolearray"zzBufferArrayL*ˆWò:Ü
PostfixExpression
internalRoleindex
operator++?

SimpleName
internalRoleoperand"zzCurrentPosL*ÖXò:*ÖXò:º
MethodInvocation
internalRoleelseExpression?

SimpleName
internalRole
expression"	zzBufferL*òXò:h6

SimpleName
internalRolename"charAt*¢Xò:iã
PostfixExpression
internalRole	arguments
operator++?

SimpleName
internalRoleoperand"zzCurrentPosL*©Xò:*©Xò:j:g:Ñ*“Wò:Ç:HΩ 
IfStatement
internalRoleelseStatement=

SimpleName
internalRole
expression"zzAtEOF*œXô:Gö
Block
internalRolethenStatement˝
ExpressionStatement
internalRole
statements∆

Assignment
internalRole
expression
operator=@

SimpleName
internalRoleleftHandSide"zzInput*ÊXö:É?

SimpleName
internalRolerightHandSide"YYEOF*Xö:Ñ*ÊXö:Ç:m
BreakStatement
internalRole
statements;

SimpleName
internalRolelabel"zzForAction*âYõ::[:H_^©
Block
internalRoleelseStatementä
ExpressionStatement
internalRole
statements”

Assignment
internalRole
expression
operator=E

SimpleName
internalRoleleftHandSide"zzCurrentPos*ÍYü:ÉG

SimpleName
internalRolerightHandSide"zzCurrentPosL*˙Yü:Ñ*ÍYü:Ç:à
ExpressionStatement
internalRole
statements—

Assignment
internalRole
expression
operator=D

SimpleName
internalRoleleftHandSide"zzMarkedPos*ïZ†:ÉF

SimpleName
internalRolerightHandSide"zzMarkedPosL*•Z†:Ñ*ïZ†:Ç:œ
VariableDeclarationStatement
internalRole
statements6
PrimitiveType
internalRoletype"boolean*øZ°⁄
VariableDeclarationFragment
internalRole	fragments2

SimpleName
internalRolename"eof*«Z°:l
MethodInvocation
internalRoleinitializer8

SimpleName
internalRolename"zzRefill*ÕZ°:i:gä
ExpressionStatement
internalRole
statements”

Assignment
internalRole
expression
operator=F

SimpleName
internalRoleleftHandSide"zzCurrentPosL*•[£:ÉF

SimpleName
internalRolerightHandSide"zzCurrentPos*∂[£:Ñ*•[£:Ç:à
ExpressionStatement
internalRole
statements—

Assignment
operator=
internalRole
expressionE

SimpleName
internalRoleleftHandSide"zzMarkedPosL*–[§:ÉE

SimpleName
internalRolerightHandSide"zzMarkedPos*·[§:Ñ*–[§:Ç:Ç
ExpressionStatement
internalRole
statementsÀ

Assignment
internalRole
expression
operator=B

SimpleName
internalRoleleftHandSide"	zzBufferL*˙[•:ÉB

SimpleName
internalRolerightHandSide"zzBuffer*ã\•:Ñ*˙[•:Ç:Ñ
ExpressionStatement
internalRole
statementsÕ

Assignment
internalRole
expression
operator=C

SimpleName
internalRoleleftHandSide"
zzEndReadL*°\¶:ÉC

SimpleName
internalRolerightHandSide"	zzEndRead*≤\¶:Ñ*°\¶:Ç:Ì
IfStatement
internalRole
statements9

SimpleName
internalRole
expression"eof*Õ\ß:Gö
Block
internalRolethenStatement˝
ExpressionStatement
internalRole
statements∆

Assignment
internalRole
expression
operator=@

SimpleName
internalRoleleftHandSide"zzInput*‚\®:É?

SimpleName
internalRolerightHandSide"YYEOF*Ï\®:Ñ*‚\®:Ç:m
BreakStatement
internalRole
statements;

SimpleName
internalRolelabel"zzForAction*á]©::[:H_^·
Block
internalRoleelseStatement≥
ExpressionStatement
internalRole
statements¸

Assignment
internalRole
expression
operator=@

SimpleName
internalRoleleftHandSide"zzInput*√]¨:ÉÙ
ParenthesizedExpression
internalRolerightHandSideµ
ConditionalExpression
internalRole
expression«
InfixExpression
internalRole
expression
operator!=E

SimpleName
internalRoleleftOperand"zzBufferArrayL*Œ]¨:5
NullLiteral
internalRolerightOperand"null:u*Œ]¨:ˆ
ArrayAccess
internalRolethenExpression>

SimpleName
internalRolearray"zzBufferArrayL*Á]¨:Ü
PostfixExpression
internalRoleindex
operator++?

SimpleName
internalRoleoperand"zzCurrentPosL*ˆ]¨:*ˆ]¨:º
MethodInvocation
internalRoleelseExpression?

SimpleName
internalRole
expression"	zzBufferL*â^¨:h6

SimpleName
internalRolename"charAt*ì^¨:iã
PostfixExpression
internalRole	arguments
operator++?

SimpleName
internalRoleoperand"zzCurrentPosL*ö^¨:*ö^¨:j:g:Ñ*√]¨:Ç::I_^"if:F:I_^"if:IF"if:F’
VariableDeclarationStatement
internalRole
statements2
PrimitiveType
internalRoletype"int*—^Ø‰
VariableDeclarationFragment
internalRole	fragments5

SimpleName
internalRolename"zzNext*’^Ø:Ú
ArrayAccess
internalRoleinitializer8

SimpleName
internalRolearray"zzTransL*ﬁ^Ø:ã
InfixExpression
internalRoleindex
operator+°
ArrayAccess
internalRoleleftOperand9

SimpleName
internalRolearray"	zzRowMapL*Ë^Ø:7

SimpleName
internalRoleindex"zzState*Ú^Ø::†
ArrayAccess
internalRolerightOperand7

SimpleName
internalRolearray"zzCMapL*˝^Ø:7

SimpleName
internalRoleindex"zzInput*Ö_Ø::*Ë^Ø:)ø
IfStatement
internalRole
statementsò
InfixExpression
internalRole
expression
operator===

SimpleName
internalRoleleftOperand"zzNext*ü_∞:å
PrefixExpression
internalRolerightOperand
operator-?
NumberLiteral
internalRoleoperand

token1*™_∞:v*©_∞:*ü_∞:Gq
BreakStatement
internalRolethenStatement;

SimpleName
internalRolelabel"zzForAction*≥_∞::H["if:F˛
ExpressionStatement
internalRole
statements«

Assignment
internalRole
expression
operator=@

SimpleName
internalRoleleftHandSide"zzState* _±:É@

SimpleName
internalRolerightHandSide"zzNext*‘_±:Ñ* _±:Ç:Ö
VariableDeclarationStatement
internalRole
statements2
PrimitiveType
internalRoletype"int*Á_≥î
VariableDeclarationFragment
internalRole	fragments;

SimpleName
internalRolename"zzAttributes*Î_≥:ú
ArrayAccess
internalRoleinitializer7

SimpleName
internalRolearray"zzAttrL*˙_≥:7

SimpleName
internalRoleindex"zzState*Ç`≥:Ê
IfStatement
internalRole
statements•
InfixExpression
internalRole
expression
operator==ë
ParenthesizedExpression
internalRoleleftOperand’
InfixExpression
internalRole
expression
operator&C

SimpleName
internalRoleleftOperand"zzAttributes*ú`¥:E
NumberLiteral
internalRolerightOperand

token1*´`¥:v*ú`¥::E
NumberLiteral
internalRolerightOperand

token1*±`¥:v*õ`¥:Gä	
Block
internalRolethenStatementÄ
ExpressionStatement
internalRole
statements…

Assignment
internalRole
expression
operator=A

SimpleName
internalRoleleftHandSide"zzAction*√`µ:ÉA

SimpleName
internalRolerightHandSide"zzState*Œ`µ:Ñ*√`µ:Ç:ä
ExpressionStatement
internalRole
statements”

Assignment
internalRole
expression
operator=E

SimpleName
internalRoleleftHandSide"zzMarkedPosL*„`∂:ÉG

SimpleName
internalRolerightHandSide"zzCurrentPosL*Ú`∂:Ñ*„`∂:Ç:Ã
IfStatement
internalRole
statements•
InfixExpression
internalRole
expression
operator==ë
ParenthesizedExpression
internalRoleleftOperand’
InfixExpression
operator&
internalRole
expressionC

SimpleName
internalRoleleftOperand"zzAttributes*ìa∑:E
NumberLiteral

token8
internalRolerightOperand*¢a∑:v*ìa∑::E
NumberLiteral
internalRolerightOperand

token8*®a∑:v*ía∑:Gq
BreakStatement
internalRolethenStatement;

SimpleName
internalRolelabel"zzForAction*≤a∑::H["if:F:H_^"if:F:W_^:U:_^à
ExpressionStatement
internalRole
statements—

Assignment
internalRole
expression
operator=D

SimpleName
internalRoleleftHandSide"zzMarkedPos*âbæ:ÉF

SimpleName
internalRolerightHandSide"zzMarkedPosL*óbæ:Ñ*âbæ:Ç:Ù%
SwitchStatement
internalRole
statementsÓ
ConditionalExpression
internalRole
expression–
InfixExpression
internalRole
expression
operator<?

SimpleName
internalRoleleftOperand"zzAction*¥b¿:E
NumberLiteral
internalRolerightOperand

token0*øb¿:v*¥b¿:A

SimpleName
internalRolethenExpression"zzAction*√b¿:¢
ArrayAccess
internalRoleelseExpression9

SimpleName
internalRolearray"	ZZ_ACTION*Œb¿:8

SimpleName
internalRoleindex"zzAction*ÿb¿:p

SwitchCase
internalRole
statementsC
NumberLiteral
internalRole
expression

token1*Úb¡:vL:K∫
Block
internalRole
statementsê
ReturnStatement
internalRole
statements‹
QualifiedName
internalRole
expressionÌ
QualifiedName
internalRole	qualifierÉ
QualifiedName
internalRole	qualifierü
QualifiedName
internalRole	qualifier7

SimpleName
internalRole	qualifier"com*âc¬:7

SimpleName
internalRolename"intellij*çc¬::2

SimpleName
internalRolename"psi*ñc¬::8

SimpleName
internalRolename"	TokenType*öc¬::<

SimpleName
internalRolename"BAD_CHARACTER*§c¬:::`:_^p

SwitchCase
internalRole
statementsC
NumberLiteral
internalRole
expression

token6*Ãcƒ:vL:Kp

SwitchCase
internalRole
statementsC
NumberLiteral

token4
internalRole
expression*„c≈:vL:Kõ
Block
internalRole
statementsr
ReturnStatement
internalRole
statements?

SimpleName
internalRole
expression"
BNF_STRING*˙c∆::`:_^p

SwitchCase
internalRole
statementsC
NumberLiteral
internalRole
expression

token7*üd»:vL:Kp

SwitchCase
internalRole
statementsC
NumberLiteral
internalRole
expression

token5*∂d…:vL:Kõ
Block
internalRole
statementsr
ReturnStatement
internalRole
statements?

SimpleName
internalRole
expression"
BNF_NUMBER*Õd ::`:_^p

SwitchCase
internalRole
statementsC
NumberLiteral
internalRole
expression

token8*ÚdÃ:vL:Kp

SwitchCase
internalRole
statementsC
NumberLiteral
internalRole
expression

token3*âeÕ:vL:Kó
Block
internalRole
statementsn
ReturnStatement
internalRole
statements;

SimpleName
internalRole
expression"BNF_ID*†eŒ::`:_^p

SwitchCase
internalRole
statementsC
NumberLiteral
internalRole
expression

token9*¡e–:vL:Kp

SwitchCase
internalRole
statementsC
NumberLiteral

token2
internalRole
expression*ÿe—:vL:K∏
Block
internalRole
statementsé
ReturnStatement
internalRole
statements⁄
QualifiedName
internalRole
expressionÌ
QualifiedName
internalRole	qualifierÉ
QualifiedName
internalRole	qualifierü
QualifiedName
internalRole	qualifier7

SimpleName
internalRole	qualifier"com*Ôe“:7

SimpleName
internalRolename"intellij*Ûe“::2

SimpleName
internalRolename"psi*¸e“::8

SimpleName
internalRolename"	TokenType*Äf“:::

SimpleName
internalRolename"WHITE_SPACE*äf“:::`:_^q

SwitchCase
internalRole
statementsD
NumberLiteral
internalRole
expression
token10*∞f‘:vL:KÂ	
IfStatement
internalRole
statementsÒ
InfixExpression
internalRole
expression
operator&& 
InfixExpression
internalRoleleftOperand
operator==>

SimpleName
internalRoleleftOperand"zzInput*⁄f÷:=

SimpleName
internalRolerightOperand"YYEOF*Âf÷:*⁄f÷:÷
InfixExpression
internalRolerightOperand
operator==B

SimpleName
internalRoleleftOperand"zzStartRead*Óf÷:D

SimpleName
internalRolerightOperand"zzCurrentPos*˝f÷:*Óf÷:*⁄f÷:G%•
Block
internalRolethenStatementê
ExpressionStatement
internalRole
statementsŸ

Assignment
internalRole
expression
operator=@

SimpleName
internalRoleleftHandSide"zzAtEOF*ôg◊:ÉR
BooleanLiteral
booleanValuetrue
internalRolerightHandSide*£g◊:oÑ*ôg◊:Ç:e
ReturnStatement
internalRole
statements2
NullLiteral
internalRole
expression"null:u:`:H_^ï
Block
internalRoleelseStatementÁ
ExpressionStatement
internalRole
statements∞
MethodInvocation
internalRole
expression;

SimpleName
internalRolename"zzScanError*Îg€:i@

SimpleName
internalRole	arguments"ZZ_NO_MATCH*˜g€:j:g::I_^"if:F0
BreakStatement
internalRole
statements:[0
BreakStatement
internalRole
statements:[0
BreakStatement
internalRole
statements:[0
BreakStatement
internalRole
statements:[0
BreakStatement
internalRole
statements:[+

SwitchCase
internalRole
statements:N:J:W_^:U:3_^*¶PÛ:E2*‘	:E::$